// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: datamanage/v1/datamanage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DataManage_SayHello_FullMethodName = "/api.datamanage.v1.DataManage/SayHello"
)

// DataManageClient is the client API for DataManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataManageClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type dataManageClient struct {
	cc grpc.ClientConnInterface
}

func NewDataManageClient(cc grpc.ClientConnInterface) DataManageClient {
	return &dataManageClient{cc}
}

func (c *dataManageClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, DataManage_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataManageServer is the server API for DataManage service.
// All implementations must embed UnimplementedDataManageServer
// for forward compatibility
type DataManageServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedDataManageServer()
}

// UnimplementedDataManageServer must be embedded to have forward compatible implementations.
type UnimplementedDataManageServer struct {
}

func (UnimplementedDataManageServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDataManageServer) mustEmbedUnimplementedDataManageServer() {}

// UnsafeDataManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataManageServer will
// result in compilation errors.
type UnsafeDataManageServer interface {
	mustEmbedUnimplementedDataManageServer()
}

func RegisterDataManageServer(s grpc.ServiceRegistrar, srv DataManageServer) {
	s.RegisterService(&DataManage_ServiceDesc, srv)
}

func _DataManage_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataManageServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataManage_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataManageServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataManage_ServiceDesc is the grpc.ServiceDesc for DataManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.datamanage.v1.DataManage",
	HandlerType: (*DataManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _DataManage_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datamanage/v1/datamanage.proto",
}
