server:
  port: 8001

app:
  upload-dir: D:/coder/code-store/go/smart_product/new-code/backend/upload

spring:
  application:
    name: knowledge-hub-backend-spring
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 220MB
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/knowledge?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      database: 6
      timeout: 200ms

logging:
  level:
    com.smartproduct: INFO

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
