services:
  mysql:
    image: mysql:8.0
    container_name: smart-product-dev-mysql
    restart: unless-stopped
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knowledge
    volumes:
      - ../dev-data/mysql:/var/lib/mysql
      - ./deploy/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "13306:3306"
    command: mysqld
    networks:
      - smart-product-dev-net

  redis:
    image: redis:6.2
    container_name: smart-product-dev-redis
    restart: unless-stopped
    volumes:
      - ./deploy/redis/redis.conf:/usr/local/redis/conf/redis.conf:ro
      - ../dev-data/redis:/data
    command: ["redis-server", "/usr/local/redis/conf/redis.conf", "--appendonly", "yes"]
    ports:
      - "16379:6379"
    networks:
      - smart-product-dev-net

networks:
  smart-product-dev-net:
    name: smart-product-dev-net
