// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: scenemanage/v1/scene_manage.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CopySceneRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CopySceneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CopySceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CopySceneRequestMultiError, or nil if none found.
func (m *CopySceneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CopySceneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSceneTemplateId() < 0 {
		err := CopySceneRequestValidationError{
			field:  "SceneTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetSceneName()); l < 1 || l > 255 {
		err := CopySceneRequestValidationError{
			field:  "SceneName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CopySceneRequestMultiError(errors)
	}

	return nil
}

// CopySceneRequestMultiError is an error wrapping multiple validation errors
// returned by CopySceneRequest.ValidateAll() if the designated constraints
// aren't met.
type CopySceneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CopySceneRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CopySceneRequestMultiError) AllErrors() []error { return m }

// CopySceneRequestValidationError is the validation error returned by
// CopySceneRequest.Validate if the designated constraints aren't met.
type CopySceneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CopySceneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CopySceneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CopySceneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CopySceneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CopySceneRequestValidationError) ErrorName() string { return "CopySceneRequestValidationError" }

// Error satisfies the builtin error interface
func (e CopySceneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCopySceneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CopySceneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CopySceneRequestValidationError{}

// Validate checks the field values on CopySceneReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CopySceneReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CopySceneReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CopySceneReplyMultiError,
// or nil if none found.
func (m *CopySceneReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CopySceneReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSceneTemplateId() < 0 {
		err := CopySceneReplyValidationError{
			field:  "SceneTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CopySceneReplyMultiError(errors)
	}

	return nil
}

// CopySceneReplyMultiError is an error wrapping multiple validation errors
// returned by CopySceneReply.ValidateAll() if the designated constraints
// aren't met.
type CopySceneReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CopySceneReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CopySceneReplyMultiError) AllErrors() []error { return m }

// CopySceneReplyValidationError is the validation error returned by
// CopySceneReply.Validate if the designated constraints aren't met.
type CopySceneReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CopySceneReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CopySceneReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CopySceneReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CopySceneReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CopySceneReplyValidationError) ErrorName() string { return "CopySceneReplyValidationError" }

// Error satisfies the builtin error interface
func (e CopySceneReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCopySceneReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CopySceneReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CopySceneReplyValidationError{}

// Validate checks the field values on DeleteSceneItemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSceneItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSceneItemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSceneItemRequestMultiError, or nil if none found.
func (m *DeleteSceneItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSceneItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SceneItemId

	if len(errors) > 0 {
		return DeleteSceneItemRequestMultiError(errors)
	}

	return nil
}

// DeleteSceneItemRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteSceneItemRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteSceneItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSceneItemRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSceneItemRequestMultiError) AllErrors() []error { return m }

// DeleteSceneItemRequestValidationError is the validation error returned by
// DeleteSceneItemRequest.Validate if the designated constraints aren't met.
type DeleteSceneItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSceneItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSceneItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSceneItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSceneItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSceneItemRequestValidationError) ErrorName() string {
	return "DeleteSceneItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSceneItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSceneItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSceneItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSceneItemRequestValidationError{}

// Validate checks the field values on SceneTemplateListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SceneTemplateListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SceneTemplateListRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SceneTemplateListRequestMultiError, or nil if none found.
func (m *SceneTemplateListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SceneTemplateListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPageSize() <= 0 {
		err := SceneTemplateListRequestValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageNumber() <= 0 {
		err := SceneTemplateListRequestValidationError{
			field:  "PageNumber",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSortBy() != "" {

		if _, ok := _SceneTemplateListRequest_SortBy_InLookup[m.GetSortBy()]; !ok {
			err := SceneTemplateListRequestValidationError{
				field:  "SortBy",
				reason: "value must be in list [id]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetOrder() != "" {

		if _, ok := _SceneTemplateListRequest_Order_InLookup[m.GetOrder()]; !ok {
			err := SceneTemplateListRequestValidationError{
				field:  "Order",
				reason: "value must be in list [asc desc]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for SearchSceneName

	if m.GetSearchSceneDisabled() != "" {

		if _, ok := _SceneTemplateListRequest_SearchSceneDisabled_InLookup[m.GetSearchSceneDisabled()]; !ok {
			err := SceneTemplateListRequestValidationError{
				field:  "SearchSceneDisabled",
				reason: "value must be in list [all disabled enabled]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return SceneTemplateListRequestMultiError(errors)
	}

	return nil
}

// SceneTemplateListRequestMultiError is an error wrapping multiple validation
// errors returned by SceneTemplateListRequest.ValidateAll() if the designated
// constraints aren't met.
type SceneTemplateListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SceneTemplateListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SceneTemplateListRequestMultiError) AllErrors() []error { return m }

// SceneTemplateListRequestValidationError is the validation error returned by
// SceneTemplateListRequest.Validate if the designated constraints aren't met.
type SceneTemplateListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SceneTemplateListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SceneTemplateListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SceneTemplateListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SceneTemplateListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SceneTemplateListRequestValidationError) ErrorName() string {
	return "SceneTemplateListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SceneTemplateListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSceneTemplateListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SceneTemplateListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SceneTemplateListRequestValidationError{}

var _SceneTemplateListRequest_SortBy_InLookup = map[string]struct{}{
	"id": {},
}

var _SceneTemplateListRequest_Order_InLookup = map[string]struct{}{
	"asc":  {},
	"desc": {},
}

var _SceneTemplateListRequest_SearchSceneDisabled_InLookup = map[string]struct{}{
	"all":      {},
	"disabled": {},
	"enabled":  {},
}

// Validate checks the field values on SceneTemplate with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SceneTemplate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SceneTemplate with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SceneTemplateMultiError, or
// nil if none found.
func (m *SceneTemplate) ValidateAll() error {
	return m.validate(true)
}

func (m *SceneTemplate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSceneTemplateId() < 0 {
		err := SceneTemplateValidationError{
			field:  "SceneTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetSceneName()); l < 1 || l > 255 {
		err := SceneTemplateValidationError{
			field:  "SceneName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for SceneIsDisabled

	// no validation rules for SceneIsUsed

	// no validation rules for CreatorName

	// no validation rules for UpdateTime

	if len(errors) > 0 {
		return SceneTemplateMultiError(errors)
	}

	return nil
}

// SceneTemplateMultiError is an error wrapping multiple validation errors
// returned by SceneTemplate.ValidateAll() if the designated constraints
// aren't met.
type SceneTemplateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SceneTemplateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SceneTemplateMultiError) AllErrors() []error { return m }

// SceneTemplateValidationError is the validation error returned by
// SceneTemplate.Validate if the designated constraints aren't met.
type SceneTemplateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SceneTemplateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SceneTemplateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SceneTemplateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SceneTemplateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SceneTemplateValidationError) ErrorName() string { return "SceneTemplateValidationError" }

// Error satisfies the builtin error interface
func (e SceneTemplateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSceneTemplate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SceneTemplateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SceneTemplateValidationError{}

// Validate checks the field values on SceneTemplateListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SceneTemplateListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SceneTemplateListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SceneTemplateListReplyMultiError, or nil if none found.
func (m *SceneTemplateListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SceneTemplateListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetContent() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SceneTemplateListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SceneTemplateListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SceneTemplateListReplyValidationError{
					field:  fmt.Sprintf("Content[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalElements

	if len(errors) > 0 {
		return SceneTemplateListReplyMultiError(errors)
	}

	return nil
}

// SceneTemplateListReplyMultiError is an error wrapping multiple validation
// errors returned by SceneTemplateListReply.ValidateAll() if the designated
// constraints aren't met.
type SceneTemplateListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SceneTemplateListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SceneTemplateListReplyMultiError) AllErrors() []error { return m }

// SceneTemplateListReplyValidationError is the validation error returned by
// SceneTemplateListReply.Validate if the designated constraints aren't met.
type SceneTemplateListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SceneTemplateListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SceneTemplateListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SceneTemplateListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SceneTemplateListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SceneTemplateListReplyValidationError) ErrorName() string {
	return "SceneTemplateListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SceneTemplateListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSceneTemplateListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SceneTemplateListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SceneTemplateListReplyValidationError{}

// Validate checks the field values on SceneDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SceneDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SceneDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SceneDetailRequestMultiError, or nil if none found.
func (m *SceneDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SceneDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSceneTemplateId() < 0 {
		err := SceneDetailRequestValidationError{
			field:  "SceneTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SceneDetailRequestMultiError(errors)
	}

	return nil
}

// SceneDetailRequestMultiError is an error wrapping multiple validation errors
// returned by SceneDetailRequest.ValidateAll() if the designated constraints
// aren't met.
type SceneDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SceneDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SceneDetailRequestMultiError) AllErrors() []error { return m }

// SceneDetailRequestValidationError is the validation error returned by
// SceneDetailRequest.Validate if the designated constraints aren't met.
type SceneDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SceneDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SceneDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SceneDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SceneDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SceneDetailRequestValidationError) ErrorName() string {
	return "SceneDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SceneDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSceneDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SceneDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SceneDetailRequestValidationError{}

// Validate checks the field values on SceneDetailReplay with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SceneDetailReplay) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SceneDetailReplay with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SceneDetailReplayMultiError, or nil if none found.
func (m *SceneDetailReplay) ValidateAll() error {
	return m.validate(true)
}

func (m *SceneDetailReplay) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSceneItem() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SceneDetailReplayValidationError{
						field:  fmt.Sprintf("SceneItem[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SceneDetailReplayValidationError{
						field:  fmt.Sprintf("SceneItem[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SceneDetailReplayValidationError{
					field:  fmt.Sprintf("SceneItem[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetSceneTemplateDetail()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SceneDetailReplayValidationError{
					field:  "SceneTemplateDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SceneDetailReplayValidationError{
					field:  "SceneTemplateDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSceneTemplateDetail()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SceneDetailReplayValidationError{
				field:  "SceneTemplateDetail",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SceneDetailReplayMultiError(errors)
	}

	return nil
}

// SceneDetailReplayMultiError is an error wrapping multiple validation errors
// returned by SceneDetailReplay.ValidateAll() if the designated constraints
// aren't met.
type SceneDetailReplayMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SceneDetailReplayMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SceneDetailReplayMultiError) AllErrors() []error { return m }

// SceneDetailReplayValidationError is the validation error returned by
// SceneDetailReplay.Validate if the designated constraints aren't met.
type SceneDetailReplayValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SceneDetailReplayValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SceneDetailReplayValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SceneDetailReplayValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SceneDetailReplayValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SceneDetailReplayValidationError) ErrorName() string {
	return "SceneDetailReplayValidationError"
}

// Error satisfies the builtin error interface
func (e SceneDetailReplayValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSceneDetailReplay.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SceneDetailReplayValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SceneDetailReplayValidationError{}

// Validate checks the field values on EditSceneRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EditSceneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditSceneRequestMultiError, or nil if none found.
func (m *EditSceneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditSceneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSceneTemplateId() < 0 {
		err := EditSceneRequestValidationError{
			field:  "SceneTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetSceneName()); l < 1 || l > 255 {
		err := EditSceneRequestValidationError{
			field:  "SceneName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetSceneItem() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EditSceneRequestValidationError{
						field:  fmt.Sprintf("SceneItem[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EditSceneRequestValidationError{
						field:  fmt.Sprintf("SceneItem[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EditSceneRequestValidationError{
					field:  fmt.Sprintf("SceneItem[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return EditSceneRequestMultiError(errors)
	}

	return nil
}

// EditSceneRequestMultiError is an error wrapping multiple validation errors
// returned by EditSceneRequest.ValidateAll() if the designated constraints
// aren't met.
type EditSceneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditSceneRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditSceneRequestMultiError) AllErrors() []error { return m }

// EditSceneRequestValidationError is the validation error returned by
// EditSceneRequest.Validate if the designated constraints aren't met.
type EditSceneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditSceneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditSceneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditSceneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditSceneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditSceneRequestValidationError) ErrorName() string { return "EditSceneRequestValidationError" }

// Error satisfies the builtin error interface
func (e EditSceneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditSceneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditSceneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditSceneRequestValidationError{}

// Validate checks the field values on EditSceneDisabledRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EditSceneDisabledRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditSceneDisabledRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditSceneDisabledRequestMultiError, or nil if none found.
func (m *EditSceneDisabledRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditSceneDisabledRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSceneTemplateId() < 0 {
		err := EditSceneDisabledRequestValidationError{
			field:  "SceneTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsDisabled

	if len(errors) > 0 {
		return EditSceneDisabledRequestMultiError(errors)
	}

	return nil
}

// EditSceneDisabledRequestMultiError is an error wrapping multiple validation
// errors returned by EditSceneDisabledRequest.ValidateAll() if the designated
// constraints aren't met.
type EditSceneDisabledRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditSceneDisabledRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditSceneDisabledRequestMultiError) AllErrors() []error { return m }

// EditSceneDisabledRequestValidationError is the validation error returned by
// EditSceneDisabledRequest.Validate if the designated constraints aren't met.
type EditSceneDisabledRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditSceneDisabledRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditSceneDisabledRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditSceneDisabledRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditSceneDisabledRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditSceneDisabledRequestValidationError) ErrorName() string {
	return "EditSceneDisabledRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EditSceneDisabledRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditSceneDisabledRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditSceneDisabledRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditSceneDisabledRequestValidationError{}

// Validate checks the field values on AddSceneItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddSceneItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddSceneItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddSceneItemMultiError, or
// nil if none found.
func (m *AddSceneItem) ValidateAll() error {
	return m.validate(true)
}

func (m *AddSceneItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if l := utf8.RuneCountInString(m.GetSceneItemName()); l < 1 || l > 255 {
		err := AddSceneItemValidationError{
			field:  "SceneItemName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AddSceneItem_Type_InLookup[m.GetType()]; !ok {
		err := AddSceneItemValidationError{
			field:  "Type",
			reason: "value must be in list [dict text integer decimal datetime picture video audio file]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DictTemplateId

	// no validation rules for MultiValue

	// no validation rules for IsHide

	// no validation rules for IsRequired

	// no validation rules for IsSupportSearch

	if m.GetSortNumber() < 1 {
		err := AddSceneItemValidationError{
			field:  "SortNumber",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddSceneItemMultiError(errors)
	}

	return nil
}

// AddSceneItemMultiError is an error wrapping multiple validation errors
// returned by AddSceneItem.ValidateAll() if the designated constraints aren't met.
type AddSceneItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddSceneItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddSceneItemMultiError) AllErrors() []error { return m }

// AddSceneItemValidationError is the validation error returned by
// AddSceneItem.Validate if the designated constraints aren't met.
type AddSceneItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddSceneItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddSceneItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddSceneItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddSceneItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddSceneItemValidationError) ErrorName() string { return "AddSceneItemValidationError" }

// Error satisfies the builtin error interface
func (e AddSceneItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddSceneItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddSceneItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddSceneItemValidationError{}

var _AddSceneItem_Type_InLookup = map[string]struct{}{
	"dict":     {},
	"text":     {},
	"integer":  {},
	"decimal":  {},
	"datetime": {},
	"picture":  {},
	"video":    {},
	"audio":    {},
	"file":     {},
}

// Validate checks the field values on CreateSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSceneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSceneRequestMultiError, or nil if none found.
func (m *CreateSceneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSceneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetSceneName()); l < 1 || l > 255 {
		err := CreateSceneRequestValidationError{
			field:  "SceneName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetSceneItem() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateSceneRequestValidationError{
						field:  fmt.Sprintf("SceneItem[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateSceneRequestValidationError{
						field:  fmt.Sprintf("SceneItem[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateSceneRequestValidationError{
					field:  fmt.Sprintf("SceneItem[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateSceneRequestMultiError(errors)
	}

	return nil
}

// CreateSceneRequestMultiError is an error wrapping multiple validation errors
// returned by CreateSceneRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateSceneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSceneRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSceneRequestMultiError) AllErrors() []error { return m }

// CreateSceneRequestValidationError is the validation error returned by
// CreateSceneRequest.Validate if the designated constraints aren't met.
type CreateSceneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSceneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSceneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSceneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSceneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSceneRequestValidationError) ErrorName() string {
	return "CreateSceneRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSceneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSceneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSceneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSceneRequestValidationError{}

// Validate checks the field values on CreateSceneReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateSceneReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSceneReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSceneReplyMultiError, or nil if none found.
func (m *CreateSceneReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSceneReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SceneTemplateId

	if len(errors) > 0 {
		return CreateSceneReplyMultiError(errors)
	}

	return nil
}

// CreateSceneReplyMultiError is an error wrapping multiple validation errors
// returned by CreateSceneReply.ValidateAll() if the designated constraints
// aren't met.
type CreateSceneReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSceneReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSceneReplyMultiError) AllErrors() []error { return m }

// CreateSceneReplyValidationError is the validation error returned by
// CreateSceneReply.Validate if the designated constraints aren't met.
type CreateSceneReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSceneReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSceneReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSceneReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSceneReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSceneReplyValidationError) ErrorName() string { return "CreateSceneReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateSceneReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSceneReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSceneReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSceneReplyValidationError{}

// Validate checks the field values on SceneDetailReplay_SceneItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SceneDetailReplay_SceneItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SceneDetailReplay_SceneItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SceneDetailReplay_SceneItemMultiError, or nil if none found.
func (m *SceneDetailReplay_SceneItem) ValidateAll() error {
	return m.validate(true)
}

func (m *SceneDetailReplay_SceneItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if _, ok := _SceneDetailReplay_SceneItem_Type_InLookup[m.GetType()]; !ok {
		err := SceneDetailReplay_SceneItemValidationError{
			field:  "Type",
			reason: "value must be in list [dict text integer decimal datetime picture video audio file]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DictTemplateId

	// no validation rules for DictTemplateName

	// no validation rules for MultiValue

	// no validation rules for IsHide

	// no validation rules for IsRequired

	// no validation rules for IsSupportSearch

	if m.GetSortNumber() < 1 {
		err := SceneDetailReplay_SceneItemValidationError{
			field:  "SortNumber",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetSceneItemName()); l < 1 || l > 255 {
		err := SceneDetailReplay_SceneItemValidationError{
			field:  "SceneItemName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SceneDetailReplay_SceneItemMultiError(errors)
	}

	return nil
}

// SceneDetailReplay_SceneItemMultiError is an error wrapping multiple
// validation errors returned by SceneDetailReplay_SceneItem.ValidateAll() if
// the designated constraints aren't met.
type SceneDetailReplay_SceneItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SceneDetailReplay_SceneItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SceneDetailReplay_SceneItemMultiError) AllErrors() []error { return m }

// SceneDetailReplay_SceneItemValidationError is the validation error returned
// by SceneDetailReplay_SceneItem.Validate if the designated constraints
// aren't met.
type SceneDetailReplay_SceneItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SceneDetailReplay_SceneItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SceneDetailReplay_SceneItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SceneDetailReplay_SceneItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SceneDetailReplay_SceneItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SceneDetailReplay_SceneItemValidationError) ErrorName() string {
	return "SceneDetailReplay_SceneItemValidationError"
}

// Error satisfies the builtin error interface
func (e SceneDetailReplay_SceneItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSceneDetailReplay_SceneItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SceneDetailReplay_SceneItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SceneDetailReplay_SceneItemValidationError{}

var _SceneDetailReplay_SceneItem_Type_InLookup = map[string]struct{}{
	"dict":     {},
	"text":     {},
	"integer":  {},
	"decimal":  {},
	"datetime": {},
	"picture":  {},
	"video":    {},
	"audio":    {},
	"file":     {},
}
