// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: scenemanage/v1/scene_manage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SceneManage_CreateScene_FullMethodName       = "/api.scenemanage.v1.SceneManage/CreateScene"
	SceneManage_CopyScene_FullMethodName         = "/api.scenemanage.v1.SceneManage/CopyScene"
	SceneManage_EditSceneDisabled_FullMethodName = "/api.scenemanage.v1.SceneManage/EditSceneDisabled"
	SceneManage_EditScene_FullMethodName         = "/api.scenemanage.v1.SceneManage/EditScene"
	SceneManage_SceneDetail_FullMethodName       = "/api.scenemanage.v1.SceneManage/SceneDetail"
	SceneManage_SceneTemplateList_FullMethodName = "/api.scenemanage.v1.SceneManage/SceneTemplateList"
	SceneManage_DeleteSceneItem_FullMethodName   = "/api.scenemanage.v1.SceneManage/DeleteSceneItem"
)

// SceneManageClient is the client API for SceneManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SceneManageClient interface {
	// 创建场景
	CreateScene(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*CreateSceneReply, error)
	// 复制场景
	CopyScene(ctx context.Context, in *CopySceneRequest, opts ...grpc.CallOption) (*CopySceneReply, error)
	// 编辑场景模版状态
	EditSceneDisabled(ctx context.Context, in *EditSceneDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 编辑场景(包括编辑名字，新增场景item，默认为可用)
	EditScene(ctx context.Context, in *EditSceneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 场景详情
	SceneDetail(ctx context.Context, in *SceneDetailRequest, opts ...grpc.CallOption) (*SceneDetailReplay, error)
	// 场景模版列表
	SceneTemplateList(ctx context.Context, in *SceneTemplateListRequest, opts ...grpc.CallOption) (*SceneTemplateListReply, error)
	// 删除场景条目
	DeleteSceneItem(ctx context.Context, in *DeleteSceneItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sceneManageClient struct {
	cc grpc.ClientConnInterface
}

func NewSceneManageClient(cc grpc.ClientConnInterface) SceneManageClient {
	return &sceneManageClient{cc}
}

func (c *sceneManageClient) CreateScene(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*CreateSceneReply, error) {
	out := new(CreateSceneReply)
	err := c.cc.Invoke(ctx, SceneManage_CreateScene_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneManageClient) CopyScene(ctx context.Context, in *CopySceneRequest, opts ...grpc.CallOption) (*CopySceneReply, error) {
	out := new(CopySceneReply)
	err := c.cc.Invoke(ctx, SceneManage_CopyScene_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneManageClient) EditSceneDisabled(ctx context.Context, in *EditSceneDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SceneManage_EditSceneDisabled_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneManageClient) EditScene(ctx context.Context, in *EditSceneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SceneManage_EditScene_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneManageClient) SceneDetail(ctx context.Context, in *SceneDetailRequest, opts ...grpc.CallOption) (*SceneDetailReplay, error) {
	out := new(SceneDetailReplay)
	err := c.cc.Invoke(ctx, SceneManage_SceneDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneManageClient) SceneTemplateList(ctx context.Context, in *SceneTemplateListRequest, opts ...grpc.CallOption) (*SceneTemplateListReply, error) {
	out := new(SceneTemplateListReply)
	err := c.cc.Invoke(ctx, SceneManage_SceneTemplateList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneManageClient) DeleteSceneItem(ctx context.Context, in *DeleteSceneItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SceneManage_DeleteSceneItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SceneManageServer is the server API for SceneManage service.
// All implementations must embed UnimplementedSceneManageServer
// for forward compatibility
type SceneManageServer interface {
	// 创建场景
	CreateScene(context.Context, *CreateSceneRequest) (*CreateSceneReply, error)
	// 复制场景
	CopyScene(context.Context, *CopySceneRequest) (*CopySceneReply, error)
	// 编辑场景模版状态
	EditSceneDisabled(context.Context, *EditSceneDisabledRequest) (*emptypb.Empty, error)
	// 编辑场景(包括编辑名字，新增场景item，默认为可用)
	EditScene(context.Context, *EditSceneRequest) (*emptypb.Empty, error)
	// 场景详情
	SceneDetail(context.Context, *SceneDetailRequest) (*SceneDetailReplay, error)
	// 场景模版列表
	SceneTemplateList(context.Context, *SceneTemplateListRequest) (*SceneTemplateListReply, error)
	// 删除场景条目
	DeleteSceneItem(context.Context, *DeleteSceneItemRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSceneManageServer()
}

// UnimplementedSceneManageServer must be embedded to have forward compatible implementations.
type UnimplementedSceneManageServer struct {
}

func (UnimplementedSceneManageServer) CreateScene(context.Context, *CreateSceneRequest) (*CreateSceneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScene not implemented")
}
func (UnimplementedSceneManageServer) CopyScene(context.Context, *CopySceneRequest) (*CopySceneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyScene not implemented")
}
func (UnimplementedSceneManageServer) EditSceneDisabled(context.Context, *EditSceneDisabledRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditSceneDisabled not implemented")
}
func (UnimplementedSceneManageServer) EditScene(context.Context, *EditSceneRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditScene not implemented")
}
func (UnimplementedSceneManageServer) SceneDetail(context.Context, *SceneDetailRequest) (*SceneDetailReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SceneDetail not implemented")
}
func (UnimplementedSceneManageServer) SceneTemplateList(context.Context, *SceneTemplateListRequest) (*SceneTemplateListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SceneTemplateList not implemented")
}
func (UnimplementedSceneManageServer) DeleteSceneItem(context.Context, *DeleteSceneItemRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSceneItem not implemented")
}
func (UnimplementedSceneManageServer) mustEmbedUnimplementedSceneManageServer() {}

// UnsafeSceneManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SceneManageServer will
// result in compilation errors.
type UnsafeSceneManageServer interface {
	mustEmbedUnimplementedSceneManageServer()
}

func RegisterSceneManageServer(s grpc.ServiceRegistrar, srv SceneManageServer) {
	s.RegisterService(&SceneManage_ServiceDesc, srv)
}

func _SceneManage_CreateScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneManageServer).CreateScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneManage_CreateScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneManageServer).CreateScene(ctx, req.(*CreateSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneManage_CopyScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopySceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneManageServer).CopyScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneManage_CopyScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneManageServer).CopyScene(ctx, req.(*CopySceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneManage_EditSceneDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSceneDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneManageServer).EditSceneDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneManage_EditSceneDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneManageServer).EditSceneDisabled(ctx, req.(*EditSceneDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneManage_EditScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneManageServer).EditScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneManage_EditScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneManageServer).EditScene(ctx, req.(*EditSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneManage_SceneDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SceneDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneManageServer).SceneDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneManage_SceneDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneManageServer).SceneDetail(ctx, req.(*SceneDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneManage_SceneTemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SceneTemplateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneManageServer).SceneTemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneManage_SceneTemplateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneManageServer).SceneTemplateList(ctx, req.(*SceneTemplateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneManage_DeleteSceneItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSceneItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneManageServer).DeleteSceneItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneManage_DeleteSceneItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneManageServer).DeleteSceneItem(ctx, req.(*DeleteSceneItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SceneManage_ServiceDesc is the grpc.ServiceDesc for SceneManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SceneManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.scenemanage.v1.SceneManage",
	HandlerType: (*SceneManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScene",
			Handler:    _SceneManage_CreateScene_Handler,
		},
		{
			MethodName: "CopyScene",
			Handler:    _SceneManage_CopyScene_Handler,
		},
		{
			MethodName: "EditSceneDisabled",
			Handler:    _SceneManage_EditSceneDisabled_Handler,
		},
		{
			MethodName: "EditScene",
			Handler:    _SceneManage_EditScene_Handler,
		},
		{
			MethodName: "SceneDetail",
			Handler:    _SceneManage_SceneDetail_Handler,
		},
		{
			MethodName: "SceneTemplateList",
			Handler:    _SceneManage_SceneTemplateList_Handler,
		},
		{
			MethodName: "DeleteSceneItem",
			Handler:    _SceneManage_DeleteSceneItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scenemanage/v1/scene_manage.proto",
}
