// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// Common
func IsDbError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_ERROR.String() && e.Code == 500
}

// Common
func ErrorDbError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsRdsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RDS_ERROR.String() && e.Code == 500
}

func ErrorRdsError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_RDS_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAMS.String() && e.Code == 400
}

func ErrorInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PARAMS.String(), fmt.Sprintf(format, args...))
}

// 第三方服务错误
func IsThirdPartyServiceErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_THIRD_PARTY_SERVICE_ERR.String() && e.Code == 500
}

// 第三方服务错误
func ErrorThirdPartyServiceErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_THIRD_PARTY_SERVICE_ERR.String(), fmt.Sprintf(format, args...))
}

func IsProtoError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PROTO_ERROR.String() && e.Code == 500
}

func ErrorProtoError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PROTO_ERROR.String(), fmt.Sprintf(format, args...))
}

// 系统错误
func IsSystemError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SYSTEM_ERROR.String() && e.Code == 500
}

// 系统错误
func ErrorSystemError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SYSTEM_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsLoginError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_LOGIN_ERROR.String() && e.Code == 401
}

func ErrorLoginError(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_LOGIN_ERROR.String(), fmt.Sprintf(format, args...))
}

// User
// Personal
func IsIncorrectOldPassword(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INCORRECT_OLD_PASSWORD.String() && e.Code == 400
}

// User
// Personal
func ErrorIncorrectOldPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INCORRECT_OLD_PASSWORD.String(), fmt.Sprintf(format, args...))
}

// 新密码格式错误
func IsInvalidNewPassword(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_NEW_PASSWORD.String() && e.Code == 400
}

// 新密码格式错误
func ErrorInvalidNewPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_NEW_PASSWORD.String(), fmt.Sprintf(format, args...))
}

// 新密码不能与原密码相同
func IsSameAsOriginalPassword(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SAME_AS_ORIGINAL_PASSWORD.String() && e.Code == 400
}

// 新密码不能与原密码相同
func ErrorSameAsOriginalPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_SAME_AS_ORIGINAL_PASSWORD.String(), fmt.Sprintf(format, args...))
}

// 修改密码失败
func IsSetPasswordFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SET_PASSWORD_FAILED.String() && e.Code == 400
}

// 修改密码失败
func ErrorSetPasswordFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_SET_PASSWORD_FAILED.String(), fmt.Sprintf(format, args...))
}

// 操作码错误
func IsInvalidOpCode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_OP_CODE.String() && e.Code == 400
}

// 操作码错误
func ErrorInvalidOpCode(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_OP_CODE.String(), fmt.Sprintf(format, args...))
}

// 验证码错误
func IsIncorrectVerificationCode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INCORRECT_VERIFICATION_CODE.String() && e.Code == 400
}

// 验证码错误
func ErrorIncorrectVerificationCode(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INCORRECT_VERIFICATION_CODE.String(), fmt.Sprintf(format, args...))
}

// 新用户名格式错误
func IsInvalidUsername(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_USERNAME.String() && e.Code == 400
}

// 新用户名格式错误
func ErrorInvalidUsername(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_USERNAME.String(), fmt.Sprintf(format, args...))
}

// 修改用户名失败
func IsUpdateUserFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UPDATE_USER_FAILED.String() && e.Code == 500
}

// 修改用户名失败
func ErrorUpdateUserFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UPDATE_USER_FAILED.String(), fmt.Sprintf(format, args...))
}

// 发送验证码失败
func IsSendEmailFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SEND_EMAIL_FAILED.String() && e.Code == 500
}

// 发送验证码失败
func ErrorSendEmailFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SEND_EMAIL_FAILED.String(), fmt.Sprintf(format, args...))
}

// 邮箱已存在
func IsEmailExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_EMAIL_EXISTS.String() && e.Code == 400
}

// 邮箱已存在
func ErrorEmailExists(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_EMAIL_EXISTS.String(), fmt.Sprintf(format, args...))
}

// 用户名已存在
func IsUsernameExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USERNAME_EXISTS.String() && e.Code == 400
}

// 用户名已存在
func ErrorUsernameExists(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_USERNAME_EXISTS.String(), fmt.Sprintf(format, args...))
}

// Console-Usr
func IsDeleteUserFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DELETE_USER_FAILED.String() && e.Code == 500
}

// Console-Usr
func ErrorDeleteUserFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DELETE_USER_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsInvalidUserId(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_USER_ID.String() && e.Code == 400
}

func ErrorInvalidUserId(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_USER_ID.String(), fmt.Sprintf(format, args...))
}

// data-manage
func IsDictParamError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DICT_PARAM_ERROR.String() && e.Code == 400
}

// data-manage
func ErrorDictParamError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DICT_PARAM_ERROR.String(), fmt.Sprintf(format, args...))
}

// scene-manage
func IsSceneParamError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SCENE_PARAM_ERROR.String() && e.Code == 400
}

// scene-manage
func ErrorSceneParamError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_SCENE_PARAM_ERROR.String(), fmt.Sprintf(format, args...))
}
