FROM m.daocloud.io/docker.io/library/node:20-alpine AS builder

WORKDIR /src
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM m.daocloud.io/docker.io/library/nginx:1.26-alpine3.19

COPY --from=builder /src/dist /usr/share/nginx/html

EXPOSE 80
