// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.2
// - protoc             v5.29.3
// source: businessmanage/v1/business_manage.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBusinessManageAddBusinessKnowledge = "/api.businessmanage.v1.BusinessManage/AddBusinessKnowledge"
const OperationBusinessManageBusinessDetail = "/api.businessmanage.v1.BusinessManage/BusinessDetail"
const OperationBusinessManageBusinessKnowledgeDataExport = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataExport"
const OperationBusinessManageBusinessKnowledgeDataImport = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataImport"
const OperationBusinessManageBusinessKnowledgeDataNumStatistics = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataNumStatistics"
const OperationBusinessManageBusinessKnowledgeDataStatisticsBySceneAndCreator = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataStatisticsBySceneAndCreator"
const OperationBusinessManageBusinessKnowledgeDetail = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDetail"
const OperationBusinessManageBusinessKnowledgeList = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeList"
const OperationBusinessManageBusinessKnowledgeSetting = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeSetting"
const OperationBusinessManageBusinessKnowledgeTemplateExport = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeTemplateExport"
const OperationBusinessManageDeleteBusinessKnowledge = "/api.businessmanage.v1.BusinessManage/DeleteBusinessKnowledge"
const OperationBusinessManageEditBusinessKnowledge = "/api.businessmanage.v1.BusinessManage/EditBusinessKnowledge"

type BusinessManageHTTPServer interface {
	// AddBusinessKnowledge 新增知识
	AddBusinessKnowledge(context.Context, *AddBusinessKnowledgeRequest) (*AddBusinessKnowledgeReply, error)
	// BusinessDetail业务详情
	BusinessDetail(context.Context, *BusinessDetailRequest) (*BusinessDetailReply, error)
	// BusinessKnowledgeDataExport 场景知识数据导出
	BusinessKnowledgeDataExport(context.Context, *BusinessKnowledgeDataExportRequest) (*BusinessKnowledgeDataExportReply, error)
	// BusinessKnowledgeDataImport 导入数据
	BusinessKnowledgeDataImport(context.Context, *BusinessKnowledgeDataImportRequest) (*emptypb.Empty, error)
	// BusinessKnowledgeDataNumStatistics 按照场景----知识数量统计
	BusinessKnowledgeDataNumStatistics(context.Context, *BusinessKnowledgeDataNumStatisticsRequest) (*BusinessKnowledgeDataNumStatisticsReply, error)
	// BusinessKnowledgeDataStatisticsBySceneAndCreator 按照场景和知识创建人----统计数据
	BusinessKnowledgeDataStatisticsBySceneAndCreator(context.Context, *BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest) (*BusinessKnowledgeDataStatisticsBySceneAndCreatorReply, error)
	// BusinessKnowledgeDetail 知识详情
	BusinessKnowledgeDetail(context.Context, *BusinessKnowledgeDetailRequest) (*BusinessKnowledgeDetailReply, error)
	// BusinessKnowledgeList 知识列表
	BusinessKnowledgeList(context.Context, *BusinessKnowledgeListRequest) (*BusinessKnowledgeListReply, error)
	// BusinessKnowledgeSetting 知识设置，修改点击次数等
	BusinessKnowledgeSetting(context.Context, *BusinessKnowledgeSettingRequest) (*emptypb.Empty, error)
	// BusinessKnowledgeTemplateExport 导出模版
	BusinessKnowledgeTemplateExport(context.Context, *BusinessKnowledgeTemplateExportRequest) (*BusinessKnowledgeTemplateExportReply, error)
	// DeleteBusinessKnowledge 删除知识
	DeleteBusinessKnowledge(context.Context, *DeleteBusinessKnowledgeRequest) (*emptypb.Empty, error)
	// EditBusinessKnowledge 编辑知识值
	EditBusinessKnowledge(context.Context, *EditBusinessKnowledgeRequest) (*emptypb.Empty, error)
}

func RegisterBusinessManageHTTPServer(s *http.Server, srv BusinessManageHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/data/business/detail", _BusinessManage_BusinessDetail0_HTTP_Handler(srv))
	r.POST("/v1/data/business/knowledge/add", _BusinessManage_AddBusinessKnowledge0_HTTP_Handler(srv))
	r.GET("/v1/data/business/knowledge/detail", _BusinessManage_BusinessKnowledgeDetail0_HTTP_Handler(srv))
	r.POST("/v1/data/business/knowledge/edit", _BusinessManage_EditBusinessKnowledge0_HTTP_Handler(srv))
	r.POST("/v1/data/business/knowledge/delete", _BusinessManage_DeleteBusinessKnowledge0_HTTP_Handler(srv))
	r.POST("/v1/data/business/knowledge/setting", _BusinessManage_BusinessKnowledgeSetting0_HTTP_Handler(srv))
	r.POST("/v1/data/business/knowledge/list", _BusinessManage_BusinessKnowledgeList0_HTTP_Handler(srv))
	r.GET("/v1/data/business/knowledge/template/export", _BusinessManage_BusinessKnowledgeTemplateExport0_HTTP_Handler(srv))
	r.POST("/v1/data/business/knowledge/data/import", _BusinessManage_BusinessKnowledgeDataImport0_HTTP_Handler(srv))
	r.GET("/v1/data/business/knowledge/data/export", _BusinessManage_BusinessKnowledgeDataExport0_HTTP_Handler(srv))
	r.GET("/v1/data/business/statistics/knowledge", _BusinessManage_BusinessKnowledgeDataNumStatistics0_HTTP_Handler(srv))
	r.GET("/v1/data/business/statistics/creator", _BusinessManage_BusinessKnowledgeDataStatisticsBySceneAndCreator0_HTTP_Handler(srv))
}

func _BusinessManage_BusinessDetail0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessDetail(ctx, req.(*BusinessDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BusinessDetailReply)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_AddBusinessKnowledge0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddBusinessKnowledgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageAddBusinessKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddBusinessKnowledge(ctx, req.(*AddBusinessKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddBusinessKnowledgeReply)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeDetail0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeDetail(ctx, req.(*BusinessKnowledgeDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BusinessKnowledgeDetailReply)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_EditBusinessKnowledge0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EditBusinessKnowledgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageEditBusinessKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EditBusinessKnowledge(ctx, req.(*EditBusinessKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_DeleteBusinessKnowledge0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteBusinessKnowledgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageDeleteBusinessKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBusinessKnowledge(ctx, req.(*DeleteBusinessKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeSetting0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeSettingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeSetting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeSetting(ctx, req.(*BusinessKnowledgeSettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeList0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeListRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeList(ctx, req.(*BusinessKnowledgeListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BusinessKnowledgeListReply)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeTemplateExport0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeTemplateExportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeTemplateExport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeTemplateExport(ctx, req.(*BusinessKnowledgeTemplateExportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BusinessKnowledgeTemplateExportReply)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeDataImport0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeDataImportRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeDataImport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeDataImport(ctx, req.(*BusinessKnowledgeDataImportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeDataExport0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeDataExportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeDataExport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeDataExport(ctx, req.(*BusinessKnowledgeDataExportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BusinessKnowledgeDataExportReply)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeDataNumStatistics0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeDataNumStatisticsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeDataNumStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeDataNumStatistics(ctx, req.(*BusinessKnowledgeDataNumStatisticsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BusinessKnowledgeDataNumStatisticsReply)
		return ctx.Result(200, reply)
	}
}

func _BusinessManage_BusinessKnowledgeDataStatisticsBySceneAndCreator0_HTTP_Handler(srv BusinessManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBusinessManageBusinessKnowledgeDataStatisticsBySceneAndCreator)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BusinessKnowledgeDataStatisticsBySceneAndCreator(ctx, req.(*BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BusinessKnowledgeDataStatisticsBySceneAndCreatorReply)
		return ctx.Result(200, reply)
	}
}

type BusinessManageHTTPClient interface {
	AddBusinessKnowledge(ctx context.Context, req *AddBusinessKnowledgeRequest, opts ...http.CallOption) (rsp *AddBusinessKnowledgeReply, err error)
	BusinessDetail(ctx context.Context, req *BusinessDetailRequest, opts ...http.CallOption) (rsp *BusinessDetailReply, err error)
	BusinessKnowledgeDataExport(ctx context.Context, req *BusinessKnowledgeDataExportRequest, opts ...http.CallOption) (rsp *BusinessKnowledgeDataExportReply, err error)
	BusinessKnowledgeDataImport(ctx context.Context, req *BusinessKnowledgeDataImportRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	BusinessKnowledgeDataNumStatistics(ctx context.Context, req *BusinessKnowledgeDataNumStatisticsRequest, opts ...http.CallOption) (rsp *BusinessKnowledgeDataNumStatisticsReply, err error)
	BusinessKnowledgeDataStatisticsBySceneAndCreator(ctx context.Context, req *BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest, opts ...http.CallOption) (rsp *BusinessKnowledgeDataStatisticsBySceneAndCreatorReply, err error)
	BusinessKnowledgeDetail(ctx context.Context, req *BusinessKnowledgeDetailRequest, opts ...http.CallOption) (rsp *BusinessKnowledgeDetailReply, err error)
	BusinessKnowledgeList(ctx context.Context, req *BusinessKnowledgeListRequest, opts ...http.CallOption) (rsp *BusinessKnowledgeListReply, err error)
	BusinessKnowledgeSetting(ctx context.Context, req *BusinessKnowledgeSettingRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	BusinessKnowledgeTemplateExport(ctx context.Context, req *BusinessKnowledgeTemplateExportRequest, opts ...http.CallOption) (rsp *BusinessKnowledgeTemplateExportReply, err error)
	DeleteBusinessKnowledge(ctx context.Context, req *DeleteBusinessKnowledgeRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	EditBusinessKnowledge(ctx context.Context, req *EditBusinessKnowledgeRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type BusinessManageHTTPClientImpl struct {
	cc *http.Client
}

func NewBusinessManageHTTPClient(client *http.Client) BusinessManageHTTPClient {
	return &BusinessManageHTTPClientImpl{client}
}

func (c *BusinessManageHTTPClientImpl) AddBusinessKnowledge(ctx context.Context, in *AddBusinessKnowledgeRequest, opts ...http.CallOption) (*AddBusinessKnowledgeReply, error) {
	var out AddBusinessKnowledgeReply
	pattern := "/v1/data/business/knowledge/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBusinessManageAddBusinessKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessDetail(ctx context.Context, in *BusinessDetailRequest, opts ...http.CallOption) (*BusinessDetailReply, error) {
	var out BusinessDetailReply
	pattern := "/v1/data/business/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeDataExport(ctx context.Context, in *BusinessKnowledgeDataExportRequest, opts ...http.CallOption) (*BusinessKnowledgeDataExportReply, error) {
	var out BusinessKnowledgeDataExportReply
	pattern := "/v1/data/business/knowledge/data/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeDataExport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeDataImport(ctx context.Context, in *BusinessKnowledgeDataImportRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/business/knowledge/data/import"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeDataImport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeDataNumStatistics(ctx context.Context, in *BusinessKnowledgeDataNumStatisticsRequest, opts ...http.CallOption) (*BusinessKnowledgeDataNumStatisticsReply, error) {
	var out BusinessKnowledgeDataNumStatisticsReply
	pattern := "/v1/data/business/statistics/knowledge"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeDataNumStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeDataStatisticsBySceneAndCreator(ctx context.Context, in *BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest, opts ...http.CallOption) (*BusinessKnowledgeDataStatisticsBySceneAndCreatorReply, error) {
	var out BusinessKnowledgeDataStatisticsBySceneAndCreatorReply
	pattern := "/v1/data/business/statistics/creator"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeDataStatisticsBySceneAndCreator))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeDetail(ctx context.Context, in *BusinessKnowledgeDetailRequest, opts ...http.CallOption) (*BusinessKnowledgeDetailReply, error) {
	var out BusinessKnowledgeDetailReply
	pattern := "/v1/data/business/knowledge/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeList(ctx context.Context, in *BusinessKnowledgeListRequest, opts ...http.CallOption) (*BusinessKnowledgeListReply, error) {
	var out BusinessKnowledgeListReply
	pattern := "/v1/data/business/knowledge/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeSetting(ctx context.Context, in *BusinessKnowledgeSettingRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/business/knowledge/setting"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeSetting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) BusinessKnowledgeTemplateExport(ctx context.Context, in *BusinessKnowledgeTemplateExportRequest, opts ...http.CallOption) (*BusinessKnowledgeTemplateExportReply, error) {
	var out BusinessKnowledgeTemplateExportReply
	pattern := "/v1/data/business/knowledge/template/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBusinessManageBusinessKnowledgeTemplateExport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) DeleteBusinessKnowledge(ctx context.Context, in *DeleteBusinessKnowledgeRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/business/knowledge/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBusinessManageDeleteBusinessKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BusinessManageHTTPClientImpl) EditBusinessKnowledge(ctx context.Context, in *EditBusinessKnowledgeRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/business/knowledge/edit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBusinessManageEditBusinessKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
