// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dictmanage/v1/dict_manage.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddDictItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddDictItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddDictItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddDictItemMultiError, or
// nil if none found.
func (m *AddDictItem) ValidateAll() error {
	return m.validate(true)
}

func (m *AddDictItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetParentId() < 0 {
		err := AddDictItemValidationError{
			field:  "ParentId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Name

	// no validation rules for Level

	// no validation rules for IsDisabled

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AddDictItemValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AddDictItemValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AddDictItemValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AddDictItemMultiError(errors)
	}

	return nil
}

// AddDictItemMultiError is an error wrapping multiple validation errors
// returned by AddDictItem.ValidateAll() if the designated constraints aren't met.
type AddDictItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddDictItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddDictItemMultiError) AllErrors() []error { return m }

// AddDictItemValidationError is the validation error returned by
// AddDictItem.Validate if the designated constraints aren't met.
type AddDictItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddDictItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddDictItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddDictItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddDictItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddDictItemValidationError) ErrorName() string { return "AddDictItemValidationError" }

// Error satisfies the builtin error interface
func (e AddDictItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddDictItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddDictItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddDictItemValidationError{}

// Validate checks the field values on Dict with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Dict) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Dict with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DictMultiError, or nil if none found.
func (m *Dict) ValidateAll() error {
	return m.validate(true)
}

func (m *Dict) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 0 {
		err := DictValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetParentId() < 0 {
		err := DictValidationError{
			field:  "ParentId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Name

	// no validation rules for Level

	// no validation rules for IsDisabled

	// no validation rules for IsUsed

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DictValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DictValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DictValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DictMultiError(errors)
	}

	return nil
}

// DictMultiError is an error wrapping multiple validation errors returned by
// Dict.ValidateAll() if the designated constraints aren't met.
type DictMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictMultiError) AllErrors() []error { return m }

// DictValidationError is the validation error returned by Dict.Validate if the
// designated constraints aren't met.
type DictValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictValidationError) ErrorName() string { return "DictValidationError" }

// Error satisfies the builtin error interface
func (e DictValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDict.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictValidationError{}

// Validate checks the field values on CreateTreeDict with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateTreeDict) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTreeDict with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateTreeDictMultiError,
// or nil if none found.
func (m *CreateTreeDict) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTreeDict) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for IsDisabled

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateTreeDictValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateTreeDictValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateTreeDictValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateTreeDictMultiError(errors)
	}

	return nil
}

// CreateTreeDictMultiError is an error wrapping multiple validation errors
// returned by CreateTreeDict.ValidateAll() if the designated constraints
// aren't met.
type CreateTreeDictMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTreeDictMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTreeDictMultiError) AllErrors() []error { return m }

// CreateTreeDictValidationError is the validation error returned by
// CreateTreeDict.Validate if the designated constraints aren't met.
type CreateTreeDictValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTreeDictValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTreeDictValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTreeDictValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTreeDictValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTreeDictValidationError) ErrorName() string { return "CreateTreeDictValidationError" }

// Error satisfies the builtin error interface
func (e CreateTreeDictValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTreeDict.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTreeDictValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTreeDictValidationError{}

// Validate checks the field values on TreeDict with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TreeDict) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TreeDict with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TreeDictMultiError, or nil
// if none found.
func (m *TreeDict) ValidateAll() error {
	return m.validate(true)
}

func (m *TreeDict) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTreeDict() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TreeDictValidationError{
						field:  fmt.Sprintf("TreeDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TreeDictValidationError{
						field:  fmt.Sprintf("TreeDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TreeDictValidationError{
					field:  fmt.Sprintf("TreeDict[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TreeDictMultiError(errors)
	}

	return nil
}

// TreeDictMultiError is an error wrapping multiple validation errors returned
// by TreeDict.ValidateAll() if the designated constraints aren't met.
type TreeDictMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TreeDictMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TreeDictMultiError) AllErrors() []error { return m }

// TreeDictValidationError is the validation error returned by
// TreeDict.Validate if the designated constraints aren't met.
type TreeDictValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TreeDictValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TreeDictValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TreeDictValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TreeDictValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TreeDictValidationError) ErrorName() string { return "TreeDictValidationError" }

// Error satisfies the builtin error interface
func (e TreeDictValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTreeDict.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TreeDictValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TreeDictValidationError{}

// Validate checks the field values on PlaneDict with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PlaneDict) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PlaneDict with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PlaneDictMultiError, or nil
// if none found.
func (m *PlaneDict) ValidateAll() error {
	return m.validate(true)
}

func (m *PlaneDict) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPlaneDict() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PlaneDictValidationError{
						field:  fmt.Sprintf("PlaneDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PlaneDictValidationError{
						field:  fmt.Sprintf("PlaneDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PlaneDictValidationError{
					field:  fmt.Sprintf("PlaneDict[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PlaneDictMultiError(errors)
	}

	return nil
}

// PlaneDictMultiError is an error wrapping multiple validation errors returned
// by PlaneDict.ValidateAll() if the designated constraints aren't met.
type PlaneDictMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlaneDictMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlaneDictMultiError) AllErrors() []error { return m }

// PlaneDictValidationError is the validation error returned by
// PlaneDict.Validate if the designated constraints aren't met.
type PlaneDictValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlaneDictValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlaneDictValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlaneDictValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlaneDictValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlaneDictValidationError) ErrorName() string { return "PlaneDictValidationError" }

// Error satisfies the builtin error interface
func (e PlaneDictValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlaneDict.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlaneDictValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlaneDictValidationError{}

// Validate checks the field values on CreatePlaneDict with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreatePlaneDict) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePlaneDict with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePlaneDictMultiError, or nil if none found.
func (m *CreatePlaneDict) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePlaneDict) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPlaneDict() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreatePlaneDictValidationError{
						field:  fmt.Sprintf("PlaneDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreatePlaneDictValidationError{
						field:  fmt.Sprintf("PlaneDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreatePlaneDictValidationError{
					field:  fmt.Sprintf("PlaneDict[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreatePlaneDictMultiError(errors)
	}

	return nil
}

// CreatePlaneDictMultiError is an error wrapping multiple validation errors
// returned by CreatePlaneDict.ValidateAll() if the designated constraints
// aren't met.
type CreatePlaneDictMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePlaneDictMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePlaneDictMultiError) AllErrors() []error { return m }

// CreatePlaneDictValidationError is the validation error returned by
// CreatePlaneDict.Validate if the designated constraints aren't met.
type CreatePlaneDictValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePlaneDictValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePlaneDictValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePlaneDictValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePlaneDictValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePlaneDictValidationError) ErrorName() string { return "CreatePlaneDictValidationError" }

// Error satisfies the builtin error interface
func (e CreatePlaneDictValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePlaneDict.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePlaneDictValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePlaneDictValidationError{}

// Validate checks the field values on CreateDictRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateDictRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDictRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDictRequestMultiError, or nil if none found.
func (m *CreateDictRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDictRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetDictName()); l < 1 || l > 255 {
		err := CreateDictRequestValidationError{
			field:  "DictName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateDictRequest_DictType_InLookup[m.GetDictType()]; !ok {
		err := CreateDictRequestValidationError{
			field:  "DictType",
			reason: "value must be in list [tree plane]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetTreeDict() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateDictRequestValidationError{
						field:  fmt.Sprintf("TreeDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateDictRequestValidationError{
						field:  fmt.Sprintf("TreeDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateDictRequestValidationError{
					field:  fmt.Sprintf("TreeDict[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPlaneDict()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateDictRequestValidationError{
					field:  "PlaneDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateDictRequestValidationError{
					field:  "PlaneDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPlaneDict()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateDictRequestValidationError{
				field:  "PlaneDict",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateDictRequestMultiError(errors)
	}

	return nil
}

// CreateDictRequestMultiError is an error wrapping multiple validation errors
// returned by CreateDictRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateDictRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDictRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDictRequestMultiError) AllErrors() []error { return m }

// CreateDictRequestValidationError is the validation error returned by
// CreateDictRequest.Validate if the designated constraints aren't met.
type CreateDictRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDictRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDictRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDictRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDictRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDictRequestValidationError) ErrorName() string {
	return "CreateDictRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDictRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDictRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDictRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDictRequestValidationError{}

var _CreateDictRequest_DictType_InLookup = map[string]struct{}{
	"tree":  {},
	"plane": {},
}

// Validate checks the field values on CreateDictReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateDictReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDictReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDictReplyMultiError, or nil if none found.
func (m *CreateDictReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDictReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DictTemplateId

	if len(errors) > 0 {
		return CreateDictReplyMultiError(errors)
	}

	return nil
}

// CreateDictReplyMultiError is an error wrapping multiple validation errors
// returned by CreateDictReply.ValidateAll() if the designated constraints
// aren't met.
type CreateDictReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDictReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDictReplyMultiError) AllErrors() []error { return m }

// CreateDictReplyValidationError is the validation error returned by
// CreateDictReply.Validate if the designated constraints aren't met.
type CreateDictReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDictReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDictReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDictReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDictReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDictReplyValidationError) ErrorName() string { return "CreateDictReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateDictReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDictReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDictReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDictReplyValidationError{}

// Validate checks the field values on EditDictRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EditDictRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditDictRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditDictRequestMultiError, or nil if none found.
func (m *EditDictRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditDictRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDictTemplateId() < 0 {
		err := EditDictRequestValidationError{
			field:  "DictTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetDictName()); l < 1 || l > 255 {
		err := EditDictRequestValidationError{
			field:  "DictName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetTreeDict() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EditDictRequestValidationError{
						field:  fmt.Sprintf("TreeDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EditDictRequestValidationError{
						field:  fmt.Sprintf("TreeDict[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EditDictRequestValidationError{
					field:  fmt.Sprintf("TreeDict[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPlaneDict()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EditDictRequestValidationError{
					field:  "PlaneDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EditDictRequestValidationError{
					field:  "PlaneDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPlaneDict()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EditDictRequestValidationError{
				field:  "PlaneDict",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IsDisabled

	if len(errors) > 0 {
		return EditDictRequestMultiError(errors)
	}

	return nil
}

// EditDictRequestMultiError is an error wrapping multiple validation errors
// returned by EditDictRequest.ValidateAll() if the designated constraints
// aren't met.
type EditDictRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditDictRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditDictRequestMultiError) AllErrors() []error { return m }

// EditDictRequestValidationError is the validation error returned by
// EditDictRequest.Validate if the designated constraints aren't met.
type EditDictRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditDictRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditDictRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditDictRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditDictRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditDictRequestValidationError) ErrorName() string { return "EditDictRequestValidationError" }

// Error satisfies the builtin error interface
func (e EditDictRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditDictRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditDictRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditDictRequestValidationError{}

// Validate checks the field values on DictTemplateListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DictTemplateListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictTemplateListRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DictTemplateListRequestMultiError, or nil if none found.
func (m *DictTemplateListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DictTemplateListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPageSize() <= 0 {
		err := DictTemplateListRequestValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageNumber() <= 0 {
		err := DictTemplateListRequestValidationError{
			field:  "PageNumber",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSortBy() != "" {

		if _, ok := _DictTemplateListRequest_SortBy_InLookup[m.GetSortBy()]; !ok {
			err := DictTemplateListRequestValidationError{
				field:  "SortBy",
				reason: "value must be in list [id]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetOrder() != "" {

		if _, ok := _DictTemplateListRequest_Order_InLookup[m.GetOrder()]; !ok {
			err := DictTemplateListRequestValidationError{
				field:  "Order",
				reason: "value must be in list [asc desc]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for SearchDictName

	if m.GetSearchDictType() != "" {

		if _, ok := _DictTemplateListRequest_SearchDictType_InLookup[m.GetSearchDictType()]; !ok {
			err := DictTemplateListRequestValidationError{
				field:  "SearchDictType",
				reason: "value must be in list [tree plane]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetSearchDictDisabled() != "" {

		if _, ok := _DictTemplateListRequest_SearchDictDisabled_InLookup[m.GetSearchDictDisabled()]; !ok {
			err := DictTemplateListRequestValidationError{
				field:  "SearchDictDisabled",
				reason: "value must be in list [all disabled enabled]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return DictTemplateListRequestMultiError(errors)
	}

	return nil
}

// DictTemplateListRequestMultiError is an error wrapping multiple validation
// errors returned by DictTemplateListRequest.ValidateAll() if the designated
// constraints aren't met.
type DictTemplateListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictTemplateListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictTemplateListRequestMultiError) AllErrors() []error { return m }

// DictTemplateListRequestValidationError is the validation error returned by
// DictTemplateListRequest.Validate if the designated constraints aren't met.
type DictTemplateListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictTemplateListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictTemplateListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictTemplateListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictTemplateListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictTemplateListRequestValidationError) ErrorName() string {
	return "DictTemplateListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DictTemplateListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictTemplateListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictTemplateListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictTemplateListRequestValidationError{}

var _DictTemplateListRequest_SortBy_InLookup = map[string]struct{}{
	"id": {},
}

var _DictTemplateListRequest_Order_InLookup = map[string]struct{}{
	"asc":  {},
	"desc": {},
}

var _DictTemplateListRequest_SearchDictType_InLookup = map[string]struct{}{
	"tree":  {},
	"plane": {},
}

var _DictTemplateListRequest_SearchDictDisabled_InLookup = map[string]struct{}{
	"all":      {},
	"disabled": {},
	"enabled":  {},
}

// Validate checks the field values on DictTemplate with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DictTemplate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictTemplate with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DictTemplateMultiError, or
// nil if none found.
func (m *DictTemplate) ValidateAll() error {
	return m.validate(true)
}

func (m *DictTemplate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDictTemplateId() < 0 {
		err := DictTemplateValidationError{
			field:  "DictTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DictName

	// no validation rules for DictType

	// no validation rules for DictDisabled

	// no validation rules for UpdateTime

	// no validation rules for CreatorName

	// no validation rules for DictIsUsed

	if len(errors) > 0 {
		return DictTemplateMultiError(errors)
	}

	return nil
}

// DictTemplateMultiError is an error wrapping multiple validation errors
// returned by DictTemplate.ValidateAll() if the designated constraints aren't met.
type DictTemplateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictTemplateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictTemplateMultiError) AllErrors() []error { return m }

// DictTemplateValidationError is the validation error returned by
// DictTemplate.Validate if the designated constraints aren't met.
type DictTemplateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictTemplateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictTemplateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictTemplateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictTemplateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictTemplateValidationError) ErrorName() string { return "DictTemplateValidationError" }

// Error satisfies the builtin error interface
func (e DictTemplateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictTemplate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictTemplateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictTemplateValidationError{}

// Validate checks the field values on DictTemplateListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DictTemplateListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictTemplateListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DictTemplateListReplyMultiError, or nil if none found.
func (m *DictTemplateListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DictTemplateListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetContent() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DictTemplateListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DictTemplateListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DictTemplateListReplyValidationError{
					field:  fmt.Sprintf("Content[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalElements

	if len(errors) > 0 {
		return DictTemplateListReplyMultiError(errors)
	}

	return nil
}

// DictTemplateListReplyMultiError is an error wrapping multiple validation
// errors returned by DictTemplateListReply.ValidateAll() if the designated
// constraints aren't met.
type DictTemplateListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictTemplateListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictTemplateListReplyMultiError) AllErrors() []error { return m }

// DictTemplateListReplyValidationError is the validation error returned by
// DictTemplateListReply.Validate if the designated constraints aren't met.
type DictTemplateListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictTemplateListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictTemplateListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictTemplateListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictTemplateListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictTemplateListReplyValidationError) ErrorName() string {
	return "DictTemplateListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DictTemplateListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictTemplateListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictTemplateListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictTemplateListReplyValidationError{}

// Validate checks the field values on EditDictDirectoryNameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EditDictDirectoryNameRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditDictDirectoryNameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditDictDirectoryNameRequestMultiError, or nil if none found.
func (m *EditDictDirectoryNameRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditDictDirectoryNameRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDictTemplateId() < 0 {
		err := EditDictDirectoryNameRequestValidationError{
			field:  "DictTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetDictDirectoryId() < 0 {
		err := EditDictDirectoryNameRequestValidationError{
			field:  "DictDirectoryId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetDictDirectoryName()); l < 1 || l > 255 {
		err := EditDictDirectoryNameRequestValidationError{
			field:  "DictDirectoryName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return EditDictDirectoryNameRequestMultiError(errors)
	}

	return nil
}

// EditDictDirectoryNameRequestMultiError is an error wrapping multiple
// validation errors returned by EditDictDirectoryNameRequest.ValidateAll() if
// the designated constraints aren't met.
type EditDictDirectoryNameRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditDictDirectoryNameRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditDictDirectoryNameRequestMultiError) AllErrors() []error { return m }

// EditDictDirectoryNameRequestValidationError is the validation error returned
// by EditDictDirectoryNameRequest.Validate if the designated constraints
// aren't met.
type EditDictDirectoryNameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditDictDirectoryNameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditDictDirectoryNameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditDictDirectoryNameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditDictDirectoryNameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditDictDirectoryNameRequestValidationError) ErrorName() string {
	return "EditDictDirectoryNameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EditDictDirectoryNameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditDictDirectoryNameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditDictDirectoryNameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditDictDirectoryNameRequestValidationError{}

// Validate checks the field values on EditDictDisabledRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EditDictDisabledRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditDictDisabledRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditDictDisabledRequestMultiError, or nil if none found.
func (m *EditDictDisabledRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditDictDisabledRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDictTemplateId() < 0 {
		err := EditDictDisabledRequestValidationError{
			field:  "DictTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsDisabled

	if len(errors) > 0 {
		return EditDictDisabledRequestMultiError(errors)
	}

	return nil
}

// EditDictDisabledRequestMultiError is an error wrapping multiple validation
// errors returned by EditDictDisabledRequest.ValidateAll() if the designated
// constraints aren't met.
type EditDictDisabledRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditDictDisabledRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditDictDisabledRequestMultiError) AllErrors() []error { return m }

// EditDictDisabledRequestValidationError is the validation error returned by
// EditDictDisabledRequest.Validate if the designated constraints aren't met.
type EditDictDisabledRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditDictDisabledRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditDictDisabledRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditDictDisabledRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditDictDisabledRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditDictDisabledRequestValidationError) ErrorName() string {
	return "EditDictDisabledRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EditDictDisabledRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditDictDisabledRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditDictDisabledRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditDictDisabledRequestValidationError{}

// Validate checks the field values on EditDictDirectoryDisabledRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *EditDictDirectoryDisabledRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditDictDirectoryDisabledRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// EditDictDirectoryDisabledRequestMultiError, or nil if none found.
func (m *EditDictDirectoryDisabledRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditDictDirectoryDisabledRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDictDirectoryId() < 0 {
		err := EditDictDirectoryDisabledRequestValidationError{
			field:  "DictDirectoryId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsDisabled

	if len(errors) > 0 {
		return EditDictDirectoryDisabledRequestMultiError(errors)
	}

	return nil
}

// EditDictDirectoryDisabledRequestMultiError is an error wrapping multiple
// validation errors returned by
// EditDictDirectoryDisabledRequest.ValidateAll() if the designated
// constraints aren't met.
type EditDictDirectoryDisabledRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditDictDirectoryDisabledRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditDictDirectoryDisabledRequestMultiError) AllErrors() []error { return m }

// EditDictDirectoryDisabledRequestValidationError is the validation error
// returned by EditDictDirectoryDisabledRequest.Validate if the designated
// constraints aren't met.
type EditDictDirectoryDisabledRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditDictDirectoryDisabledRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditDictDirectoryDisabledRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditDictDirectoryDisabledRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditDictDirectoryDisabledRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditDictDirectoryDisabledRequestValidationError) ErrorName() string {
	return "EditDictDirectoryDisabledRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EditDictDirectoryDisabledRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditDictDirectoryDisabledRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditDictDirectoryDisabledRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditDictDirectoryDisabledRequestValidationError{}

// Validate checks the field values on DeleteDictDirectoryRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDictDirectoryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDictDirectoryRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDictDirectoryRequestMultiError, or nil if none found.
func (m *DeleteDictDirectoryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDictDirectoryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDictDirectoryId() < 0 {
		err := DeleteDictDirectoryRequestValidationError{
			field:  "DictDirectoryId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteDictDirectoryRequestMultiError(errors)
	}

	return nil
}

// DeleteDictDirectoryRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteDictDirectoryRequest.ValidateAll() if
// the designated constraints aren't met.
type DeleteDictDirectoryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDictDirectoryRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDictDirectoryRequestMultiError) AllErrors() []error { return m }

// DeleteDictDirectoryRequestValidationError is the validation error returned
// by DeleteDictDirectoryRequest.Validate if the designated constraints aren't met.
type DeleteDictDirectoryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDictDirectoryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDictDirectoryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDictDirectoryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDictDirectoryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDictDirectoryRequestValidationError) ErrorName() string {
	return "DeleteDictDirectoryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDictDirectoryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDictDirectoryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDictDirectoryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDictDirectoryRequestValidationError{}

// Validate checks the field values on DictDetailRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DictDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DictDetailRequestMultiError, or nil if none found.
func (m *DictDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DictDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDictTemplateId() < 0 {
		err := DictDetailRequestValidationError{
			field:  "DictTemplateId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DictDetailRequestMultiError(errors)
	}

	return nil
}

// DictDetailRequestMultiError is an error wrapping multiple validation errors
// returned by DictDetailRequest.ValidateAll() if the designated constraints
// aren't met.
type DictDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictDetailRequestMultiError) AllErrors() []error { return m }

// DictDetailRequestValidationError is the validation error returned by
// DictDetailRequest.Validate if the designated constraints aren't met.
type DictDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictDetailRequestValidationError) ErrorName() string {
	return "DictDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DictDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictDetailRequestValidationError{}

// Validate checks the field values on DictDetailReplay with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DictDetailReplay) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictDetailReplay with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DictDetailReplayMultiError, or nil if none found.
func (m *DictDetailReplay) ValidateAll() error {
	return m.validate(true)
}

func (m *DictDetailReplay) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDictTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DictDetailReplayValidationError{
					field:  "DictTemplate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DictDetailReplayValidationError{
					field:  "DictTemplate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDictTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DictDetailReplayValidationError{
				field:  "DictTemplate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTreeDict()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DictDetailReplayValidationError{
					field:  "TreeDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DictDetailReplayValidationError{
					field:  "TreeDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTreeDict()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DictDetailReplayValidationError{
				field:  "TreeDict",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPlaneDict()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DictDetailReplayValidationError{
					field:  "PlaneDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DictDetailReplayValidationError{
					field:  "PlaneDict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPlaneDict()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DictDetailReplayValidationError{
				field:  "PlaneDict",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DictDetailReplayMultiError(errors)
	}

	return nil
}

// DictDetailReplayMultiError is an error wrapping multiple validation errors
// returned by DictDetailReplay.ValidateAll() if the designated constraints
// aren't met.
type DictDetailReplayMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictDetailReplayMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictDetailReplayMultiError) AllErrors() []error { return m }

// DictDetailReplayValidationError is the validation error returned by
// DictDetailReplay.Validate if the designated constraints aren't met.
type DictDetailReplayValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictDetailReplayValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictDetailReplayValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictDetailReplayValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictDetailReplayValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictDetailReplayValidationError) ErrorName() string { return "DictDetailReplayValidationError" }

// Error satisfies the builtin error interface
func (e DictDetailReplayValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictDetailReplay.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictDetailReplayValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictDetailReplayValidationError{}

// Validate checks the field values on PlaneDict_Plane with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PlaneDict_Plane) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PlaneDict_Plane with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PlaneDict_PlaneMultiError, or nil if none found.
func (m *PlaneDict_Plane) ValidateAll() error {
	return m.validate(true)
}

func (m *PlaneDict_Plane) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 0 {
		err := PlaneDict_PlaneValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsDisabled

	// no validation rules for Name

	// no validation rules for IsUsed

	if len(errors) > 0 {
		return PlaneDict_PlaneMultiError(errors)
	}

	return nil
}

// PlaneDict_PlaneMultiError is an error wrapping multiple validation errors
// returned by PlaneDict_Plane.ValidateAll() if the designated constraints
// aren't met.
type PlaneDict_PlaneMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlaneDict_PlaneMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlaneDict_PlaneMultiError) AllErrors() []error { return m }

// PlaneDict_PlaneValidationError is the validation error returned by
// PlaneDict_Plane.Validate if the designated constraints aren't met.
type PlaneDict_PlaneValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlaneDict_PlaneValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlaneDict_PlaneValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlaneDict_PlaneValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlaneDict_PlaneValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlaneDict_PlaneValidationError) ErrorName() string { return "PlaneDict_PlaneValidationError" }

// Error satisfies the builtin error interface
func (e PlaneDict_PlaneValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlaneDict_Plane.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlaneDict_PlaneValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlaneDict_PlaneValidationError{}

// Validate checks the field values on CreatePlaneDict_Plane with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreatePlaneDict_Plane) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePlaneDict_Plane with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePlaneDict_PlaneMultiError, or nil if none found.
func (m *CreatePlaneDict_Plane) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePlaneDict_Plane) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsDisabled

	// no validation rules for Name

	if len(errors) > 0 {
		return CreatePlaneDict_PlaneMultiError(errors)
	}

	return nil
}

// CreatePlaneDict_PlaneMultiError is an error wrapping multiple validation
// errors returned by CreatePlaneDict_Plane.ValidateAll() if the designated
// constraints aren't met.
type CreatePlaneDict_PlaneMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePlaneDict_PlaneMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePlaneDict_PlaneMultiError) AllErrors() []error { return m }

// CreatePlaneDict_PlaneValidationError is the validation error returned by
// CreatePlaneDict_Plane.Validate if the designated constraints aren't met.
type CreatePlaneDict_PlaneValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePlaneDict_PlaneValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePlaneDict_PlaneValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePlaneDict_PlaneValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePlaneDict_PlaneValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePlaneDict_PlaneValidationError) ErrorName() string {
	return "CreatePlaneDict_PlaneValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePlaneDict_PlaneValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePlaneDict_Plane.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePlaneDict_PlaneValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePlaneDict_PlaneValidationError{}
