// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: dictmanage/v1/dict_manage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DictManage_CreateDict_FullMethodName                = "/api.dictmanage.v1.DictManage/CreateDict"
	DictManage_EditDict_FullMethodName                  = "/api.dictmanage.v1.DictManage/EditDict"
	DictManage_EditDictDisabled_FullMethodName          = "/api.dictmanage.v1.DictManage/EditDictDisabled"
	DictManage_DictTemplateList_FullMethodName          = "/api.dictmanage.v1.DictManage/DictTemplateList"
	DictManage_EditDictDirectoryName_FullMethodName     = "/api.dictmanage.v1.DictManage/EditDictDirectoryName"
	DictManage_EditDictDirectoryDisabled_FullMethodName = "/api.dictmanage.v1.DictManage/EditDictDirectoryDisabled"
	DictManage_DeleteDictDirectory_FullMethodName       = "/api.dictmanage.v1.DictManage/DeleteDictDirectory"
	DictManage_DictDetail_FullMethodName                = "/api.dictmanage.v1.DictManage/DictDetail"
)

// DictManageClient is the client API for DictManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DictManageClient interface {
	// 创建字典
	CreateDict(ctx context.Context, in *CreateDictRequest, opts ...grpc.CallOption) (*CreateDictReply, error)
	// 编辑字典(只会新增目录，默认为可用)
	EditDict(ctx context.Context, in *EditDictRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 编辑字典模版状态
	EditDictDisabled(ctx context.Context, in *EditDictDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 字典模版列表
	DictTemplateList(ctx context.Context, in *DictTemplateListRequest, opts ...grpc.CallOption) (*DictTemplateListReply, error)
	// 编辑字典目录名字
	EditDictDirectoryName(ctx context.Context, in *EditDictDirectoryNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 编辑字典目录是否可用
	EditDictDirectoryDisabled(ctx context.Context, in *EditDictDirectoryDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除字典目录（级联删除）
	DeleteDictDirectory(ctx context.Context, in *DeleteDictDirectoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 字典详情(包括字典名字，目录结构)
	DictDetail(ctx context.Context, in *DictDetailRequest, opts ...grpc.CallOption) (*DictDetailReplay, error)
}

type dictManageClient struct {
	cc grpc.ClientConnInterface
}

func NewDictManageClient(cc grpc.ClientConnInterface) DictManageClient {
	return &dictManageClient{cc}
}

func (c *dictManageClient) CreateDict(ctx context.Context, in *CreateDictRequest, opts ...grpc.CallOption) (*CreateDictReply, error) {
	out := new(CreateDictReply)
	err := c.cc.Invoke(ctx, DictManage_CreateDict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictManageClient) EditDict(ctx context.Context, in *EditDictRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DictManage_EditDict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictManageClient) EditDictDisabled(ctx context.Context, in *EditDictDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DictManage_EditDictDisabled_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictManageClient) DictTemplateList(ctx context.Context, in *DictTemplateListRequest, opts ...grpc.CallOption) (*DictTemplateListReply, error) {
	out := new(DictTemplateListReply)
	err := c.cc.Invoke(ctx, DictManage_DictTemplateList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictManageClient) EditDictDirectoryName(ctx context.Context, in *EditDictDirectoryNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DictManage_EditDictDirectoryName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictManageClient) EditDictDirectoryDisabled(ctx context.Context, in *EditDictDirectoryDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DictManage_EditDictDirectoryDisabled_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictManageClient) DeleteDictDirectory(ctx context.Context, in *DeleteDictDirectoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DictManage_DeleteDictDirectory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictManageClient) DictDetail(ctx context.Context, in *DictDetailRequest, opts ...grpc.CallOption) (*DictDetailReplay, error) {
	out := new(DictDetailReplay)
	err := c.cc.Invoke(ctx, DictManage_DictDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictManageServer is the server API for DictManage service.
// All implementations must embed UnimplementedDictManageServer
// for forward compatibility
type DictManageServer interface {
	// 创建字典
	CreateDict(context.Context, *CreateDictRequest) (*CreateDictReply, error)
	// 编辑字典(只会新增目录，默认为可用)
	EditDict(context.Context, *EditDictRequest) (*emptypb.Empty, error)
	// 编辑字典模版状态
	EditDictDisabled(context.Context, *EditDictDisabledRequest) (*emptypb.Empty, error)
	// 字典模版列表
	DictTemplateList(context.Context, *DictTemplateListRequest) (*DictTemplateListReply, error)
	// 编辑字典目录名字
	EditDictDirectoryName(context.Context, *EditDictDirectoryNameRequest) (*emptypb.Empty, error)
	// 编辑字典目录是否可用
	EditDictDirectoryDisabled(context.Context, *EditDictDirectoryDisabledRequest) (*emptypb.Empty, error)
	// 删除字典目录（级联删除）
	DeleteDictDirectory(context.Context, *DeleteDictDirectoryRequest) (*emptypb.Empty, error)
	// 字典详情(包括字典名字，目录结构)
	DictDetail(context.Context, *DictDetailRequest) (*DictDetailReplay, error)
	mustEmbedUnimplementedDictManageServer()
}

// UnimplementedDictManageServer must be embedded to have forward compatible implementations.
type UnimplementedDictManageServer struct {
}

func (UnimplementedDictManageServer) CreateDict(context.Context, *CreateDictRequest) (*CreateDictReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDict not implemented")
}
func (UnimplementedDictManageServer) EditDict(context.Context, *EditDictRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditDict not implemented")
}
func (UnimplementedDictManageServer) EditDictDisabled(context.Context, *EditDictDisabledRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditDictDisabled not implemented")
}
func (UnimplementedDictManageServer) DictTemplateList(context.Context, *DictTemplateListRequest) (*DictTemplateListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictTemplateList not implemented")
}
func (UnimplementedDictManageServer) EditDictDirectoryName(context.Context, *EditDictDirectoryNameRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditDictDirectoryName not implemented")
}
func (UnimplementedDictManageServer) EditDictDirectoryDisabled(context.Context, *EditDictDirectoryDisabledRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditDictDirectoryDisabled not implemented")
}
func (UnimplementedDictManageServer) DeleteDictDirectory(context.Context, *DeleteDictDirectoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDictDirectory not implemented")
}
func (UnimplementedDictManageServer) DictDetail(context.Context, *DictDetailRequest) (*DictDetailReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictDetail not implemented")
}
func (UnimplementedDictManageServer) mustEmbedUnimplementedDictManageServer() {}

// UnsafeDictManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DictManageServer will
// result in compilation errors.
type UnsafeDictManageServer interface {
	mustEmbedUnimplementedDictManageServer()
}

func RegisterDictManageServer(s grpc.ServiceRegistrar, srv DictManageServer) {
	s.RegisterService(&DictManage_ServiceDesc, srv)
}

func _DictManage_CreateDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).CreateDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_CreateDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).CreateDict(ctx, req.(*CreateDictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictManage_EditDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).EditDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_EditDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).EditDict(ctx, req.(*EditDictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictManage_EditDictDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDictDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).EditDictDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_EditDictDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).EditDictDisabled(ctx, req.(*EditDictDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictManage_DictTemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictTemplateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).DictTemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_DictTemplateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).DictTemplateList(ctx, req.(*DictTemplateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictManage_EditDictDirectoryName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDictDirectoryNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).EditDictDirectoryName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_EditDictDirectoryName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).EditDictDirectoryName(ctx, req.(*EditDictDirectoryNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictManage_EditDictDirectoryDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDictDirectoryDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).EditDictDirectoryDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_EditDictDirectoryDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).EditDictDirectoryDisabled(ctx, req.(*EditDictDirectoryDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictManage_DeleteDictDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDictDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).DeleteDictDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_DeleteDictDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).DeleteDictDirectory(ctx, req.(*DeleteDictDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictManage_DictDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictManageServer).DictDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictManage_DictDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictManageServer).DictDetail(ctx, req.(*DictDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DictManage_ServiceDesc is the grpc.ServiceDesc for DictManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DictManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.dictmanage.v1.DictManage",
	HandlerType: (*DictManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDict",
			Handler:    _DictManage_CreateDict_Handler,
		},
		{
			MethodName: "EditDict",
			Handler:    _DictManage_EditDict_Handler,
		},
		{
			MethodName: "EditDictDisabled",
			Handler:    _DictManage_EditDictDisabled_Handler,
		},
		{
			MethodName: "DictTemplateList",
			Handler:    _DictManage_DictTemplateList_Handler,
		},
		{
			MethodName: "EditDictDirectoryName",
			Handler:    _DictManage_EditDictDirectoryName_Handler,
		},
		{
			MethodName: "EditDictDirectoryDisabled",
			Handler:    _DictManage_EditDictDirectoryDisabled_Handler,
		},
		{
			MethodName: "DeleteDictDirectory",
			Handler:    _DictManage_DeleteDictDirectory_Handler,
		},
		{
			MethodName: "DictDetail",
			Handler:    _DictManage_DictDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictmanage/v1/dict_manage.proto",
}
