// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: businessmanage/v1/business_manage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BusinessManage_BusinessDetail_FullMethodName                                   = "/api.businessmanage.v1.BusinessManage/BusinessDetail"
	BusinessManage_AddBusinessKnowledge_FullMethodName                             = "/api.businessmanage.v1.BusinessManage/AddBusinessKnowledge"
	BusinessManage_BusinessKnowledgeDetail_FullMethodName                          = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDetail"
	BusinessManage_EditBusinessKnowledge_FullMethodName                            = "/api.businessmanage.v1.BusinessManage/EditBusinessKnowledge"
	BusinessManage_DeleteBusinessKnowledge_FullMethodName                          = "/api.businessmanage.v1.BusinessManage/DeleteBusinessKnowledge"
	BusinessManage_BusinessKnowledgeSetting_FullMethodName                         = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeSetting"
	BusinessManage_BusinessKnowledgeList_FullMethodName                            = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeList"
	BusinessManage_BusinessKnowledgeTemplateExport_FullMethodName                  = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeTemplateExport"
	BusinessManage_BusinessKnowledgeDataImport_FullMethodName                      = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataImport"
	BusinessManage_BusinessKnowledgeDataExport_FullMethodName                      = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataExport"
	BusinessManage_BusinessKnowledgeDataNumStatistics_FullMethodName               = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataNumStatistics"
	BusinessManage_BusinessKnowledgeDataStatisticsBySceneAndCreator_FullMethodName = "/api.businessmanage.v1.BusinessManage/BusinessKnowledgeDataStatisticsBySceneAndCreator"
)

// BusinessManageClient is the client API for BusinessManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusinessManageClient interface {
	// 业务详情
	BusinessDetail(ctx context.Context, in *BusinessDetailRequest, opts ...grpc.CallOption) (*BusinessDetailReply, error)
	// 新增知识
	AddBusinessKnowledge(ctx context.Context, in *AddBusinessKnowledgeRequest, opts ...grpc.CallOption) (*AddBusinessKnowledgeReply, error)
	// 知识详情
	BusinessKnowledgeDetail(ctx context.Context, in *BusinessKnowledgeDetailRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDetailReply, error)
	// 编辑知识值
	EditBusinessKnowledge(ctx context.Context, in *EditBusinessKnowledgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除知识
	DeleteBusinessKnowledge(ctx context.Context, in *DeleteBusinessKnowledgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 知识设置，修改点击次数等
	BusinessKnowledgeSetting(ctx context.Context, in *BusinessKnowledgeSettingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 知识列表
	BusinessKnowledgeList(ctx context.Context, in *BusinessKnowledgeListRequest, opts ...grpc.CallOption) (*BusinessKnowledgeListReply, error)
	// 导出模版
	BusinessKnowledgeTemplateExport(ctx context.Context, in *BusinessKnowledgeTemplateExportRequest, opts ...grpc.CallOption) (*BusinessKnowledgeTemplateExportReply, error)
	// 导入数据
	BusinessKnowledgeDataImport(ctx context.Context, in *BusinessKnowledgeDataImportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 场景知识数据导出
	BusinessKnowledgeDataExport(ctx context.Context, in *BusinessKnowledgeDataExportRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDataExportReply, error)
	// 按照场景----知识数量统计
	BusinessKnowledgeDataNumStatistics(ctx context.Context, in *BusinessKnowledgeDataNumStatisticsRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDataNumStatisticsReply, error)
	// 按照场景和知识创建人----统计数据
	BusinessKnowledgeDataStatisticsBySceneAndCreator(ctx context.Context, in *BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDataStatisticsBySceneAndCreatorReply, error)
}

type businessManageClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessManageClient(cc grpc.ClientConnInterface) BusinessManageClient {
	return &businessManageClient{cc}
}

func (c *businessManageClient) BusinessDetail(ctx context.Context, in *BusinessDetailRequest, opts ...grpc.CallOption) (*BusinessDetailReply, error) {
	out := new(BusinessDetailReply)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) AddBusinessKnowledge(ctx context.Context, in *AddBusinessKnowledgeRequest, opts ...grpc.CallOption) (*AddBusinessKnowledgeReply, error) {
	out := new(AddBusinessKnowledgeReply)
	err := c.cc.Invoke(ctx, BusinessManage_AddBusinessKnowledge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeDetail(ctx context.Context, in *BusinessKnowledgeDetailRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDetailReply, error) {
	out := new(BusinessKnowledgeDetailReply)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) EditBusinessKnowledge(ctx context.Context, in *EditBusinessKnowledgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BusinessManage_EditBusinessKnowledge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) DeleteBusinessKnowledge(ctx context.Context, in *DeleteBusinessKnowledgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BusinessManage_DeleteBusinessKnowledge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeSetting(ctx context.Context, in *BusinessKnowledgeSettingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeSetting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeList(ctx context.Context, in *BusinessKnowledgeListRequest, opts ...grpc.CallOption) (*BusinessKnowledgeListReply, error) {
	out := new(BusinessKnowledgeListReply)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeTemplateExport(ctx context.Context, in *BusinessKnowledgeTemplateExportRequest, opts ...grpc.CallOption) (*BusinessKnowledgeTemplateExportReply, error) {
	out := new(BusinessKnowledgeTemplateExportReply)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeTemplateExport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeDataImport(ctx context.Context, in *BusinessKnowledgeDataImportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeDataImport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeDataExport(ctx context.Context, in *BusinessKnowledgeDataExportRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDataExportReply, error) {
	out := new(BusinessKnowledgeDataExportReply)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeDataExport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeDataNumStatistics(ctx context.Context, in *BusinessKnowledgeDataNumStatisticsRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDataNumStatisticsReply, error) {
	out := new(BusinessKnowledgeDataNumStatisticsReply)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeDataNumStatistics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessManageClient) BusinessKnowledgeDataStatisticsBySceneAndCreator(ctx context.Context, in *BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest, opts ...grpc.CallOption) (*BusinessKnowledgeDataStatisticsBySceneAndCreatorReply, error) {
	out := new(BusinessKnowledgeDataStatisticsBySceneAndCreatorReply)
	err := c.cc.Invoke(ctx, BusinessManage_BusinessKnowledgeDataStatisticsBySceneAndCreator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessManageServer is the server API for BusinessManage service.
// All implementations must embed UnimplementedBusinessManageServer
// for forward compatibility
type BusinessManageServer interface {
	// 业务详情
	BusinessDetail(context.Context, *BusinessDetailRequest) (*BusinessDetailReply, error)
	// 新增知识
	AddBusinessKnowledge(context.Context, *AddBusinessKnowledgeRequest) (*AddBusinessKnowledgeReply, error)
	// 知识详情
	BusinessKnowledgeDetail(context.Context, *BusinessKnowledgeDetailRequest) (*BusinessKnowledgeDetailReply, error)
	// 编辑知识值
	EditBusinessKnowledge(context.Context, *EditBusinessKnowledgeRequest) (*emptypb.Empty, error)
	// 删除知识
	DeleteBusinessKnowledge(context.Context, *DeleteBusinessKnowledgeRequest) (*emptypb.Empty, error)
	// 知识设置，修改点击次数等
	BusinessKnowledgeSetting(context.Context, *BusinessKnowledgeSettingRequest) (*emptypb.Empty, error)
	// 知识列表
	BusinessKnowledgeList(context.Context, *BusinessKnowledgeListRequest) (*BusinessKnowledgeListReply, error)
	// 导出模版
	BusinessKnowledgeTemplateExport(context.Context, *BusinessKnowledgeTemplateExportRequest) (*BusinessKnowledgeTemplateExportReply, error)
	// 导入数据
	BusinessKnowledgeDataImport(context.Context, *BusinessKnowledgeDataImportRequest) (*emptypb.Empty, error)
	// 场景知识数据导出
	BusinessKnowledgeDataExport(context.Context, *BusinessKnowledgeDataExportRequest) (*BusinessKnowledgeDataExportReply, error)
	// 按照场景----知识数量统计
	BusinessKnowledgeDataNumStatistics(context.Context, *BusinessKnowledgeDataNumStatisticsRequest) (*BusinessKnowledgeDataNumStatisticsReply, error)
	// 按照场景和知识创建人----统计数据
	BusinessKnowledgeDataStatisticsBySceneAndCreator(context.Context, *BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest) (*BusinessKnowledgeDataStatisticsBySceneAndCreatorReply, error)
	mustEmbedUnimplementedBusinessManageServer()
}

// UnimplementedBusinessManageServer must be embedded to have forward compatible implementations.
type UnimplementedBusinessManageServer struct {
}

func (UnimplementedBusinessManageServer) BusinessDetail(context.Context, *BusinessDetailRequest) (*BusinessDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessDetail not implemented")
}
func (UnimplementedBusinessManageServer) AddBusinessKnowledge(context.Context, *AddBusinessKnowledgeRequest) (*AddBusinessKnowledgeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBusinessKnowledge not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeDetail(context.Context, *BusinessKnowledgeDetailRequest) (*BusinessKnowledgeDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeDetail not implemented")
}
func (UnimplementedBusinessManageServer) EditBusinessKnowledge(context.Context, *EditBusinessKnowledgeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditBusinessKnowledge not implemented")
}
func (UnimplementedBusinessManageServer) DeleteBusinessKnowledge(context.Context, *DeleteBusinessKnowledgeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBusinessKnowledge not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeSetting(context.Context, *BusinessKnowledgeSettingRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeSetting not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeList(context.Context, *BusinessKnowledgeListRequest) (*BusinessKnowledgeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeList not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeTemplateExport(context.Context, *BusinessKnowledgeTemplateExportRequest) (*BusinessKnowledgeTemplateExportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeTemplateExport not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeDataImport(context.Context, *BusinessKnowledgeDataImportRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeDataImport not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeDataExport(context.Context, *BusinessKnowledgeDataExportRequest) (*BusinessKnowledgeDataExportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeDataExport not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeDataNumStatistics(context.Context, *BusinessKnowledgeDataNumStatisticsRequest) (*BusinessKnowledgeDataNumStatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeDataNumStatistics not implemented")
}
func (UnimplementedBusinessManageServer) BusinessKnowledgeDataStatisticsBySceneAndCreator(context.Context, *BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest) (*BusinessKnowledgeDataStatisticsBySceneAndCreatorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessKnowledgeDataStatisticsBySceneAndCreator not implemented")
}
func (UnimplementedBusinessManageServer) mustEmbedUnimplementedBusinessManageServer() {}

// UnsafeBusinessManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessManageServer will
// result in compilation errors.
type UnsafeBusinessManageServer interface {
	mustEmbedUnimplementedBusinessManageServer()
}

func RegisterBusinessManageServer(s grpc.ServiceRegistrar, srv BusinessManageServer) {
	s.RegisterService(&BusinessManage_ServiceDesc, srv)
}

func _BusinessManage_BusinessDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessDetail(ctx, req.(*BusinessDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_AddBusinessKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBusinessKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).AddBusinessKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_AddBusinessKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).AddBusinessKnowledge(ctx, req.(*AddBusinessKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeDetail(ctx, req.(*BusinessKnowledgeDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_EditBusinessKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditBusinessKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).EditBusinessKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_EditBusinessKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).EditBusinessKnowledge(ctx, req.(*EditBusinessKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_DeleteBusinessKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBusinessKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).DeleteBusinessKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_DeleteBusinessKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).DeleteBusinessKnowledge(ctx, req.(*DeleteBusinessKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeSetting(ctx, req.(*BusinessKnowledgeSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeList(ctx, req.(*BusinessKnowledgeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeTemplateExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeTemplateExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeTemplateExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeTemplateExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeTemplateExport(ctx, req.(*BusinessKnowledgeTemplateExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeDataImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeDataImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeDataImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeDataImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeDataImport(ctx, req.(*BusinessKnowledgeDataImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeDataExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeDataExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeDataExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeDataExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeDataExport(ctx, req.(*BusinessKnowledgeDataExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeDataNumStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeDataNumStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeDataNumStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeDataNumStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeDataNumStatistics(ctx, req.(*BusinessKnowledgeDataNumStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessManage_BusinessKnowledgeDataStatisticsBySceneAndCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessManageServer).BusinessKnowledgeDataStatisticsBySceneAndCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessManage_BusinessKnowledgeDataStatisticsBySceneAndCreator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessManageServer).BusinessKnowledgeDataStatisticsBySceneAndCreator(ctx, req.(*BusinessKnowledgeDataStatisticsBySceneAndCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusinessManage_ServiceDesc is the grpc.ServiceDesc for BusinessManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusinessManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.businessmanage.v1.BusinessManage",
	HandlerType: (*BusinessManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BusinessDetail",
			Handler:    _BusinessManage_BusinessDetail_Handler,
		},
		{
			MethodName: "AddBusinessKnowledge",
			Handler:    _BusinessManage_AddBusinessKnowledge_Handler,
		},
		{
			MethodName: "BusinessKnowledgeDetail",
			Handler:    _BusinessManage_BusinessKnowledgeDetail_Handler,
		},
		{
			MethodName: "EditBusinessKnowledge",
			Handler:    _BusinessManage_EditBusinessKnowledge_Handler,
		},
		{
			MethodName: "DeleteBusinessKnowledge",
			Handler:    _BusinessManage_DeleteBusinessKnowledge_Handler,
		},
		{
			MethodName: "BusinessKnowledgeSetting",
			Handler:    _BusinessManage_BusinessKnowledgeSetting_Handler,
		},
		{
			MethodName: "BusinessKnowledgeList",
			Handler:    _BusinessManage_BusinessKnowledgeList_Handler,
		},
		{
			MethodName: "BusinessKnowledgeTemplateExport",
			Handler:    _BusinessManage_BusinessKnowledgeTemplateExport_Handler,
		},
		{
			MethodName: "BusinessKnowledgeDataImport",
			Handler:    _BusinessManage_BusinessKnowledgeDataImport_Handler,
		},
		{
			MethodName: "BusinessKnowledgeDataExport",
			Handler:    _BusinessManage_BusinessKnowledgeDataExport_Handler,
		},
		{
			MethodName: "BusinessKnowledgeDataNumStatistics",
			Handler:    _BusinessManage_BusinessKnowledgeDataNumStatistics_Handler,
		},
		{
			MethodName: "BusinessKnowledgeDataStatisticsBySceneAndCreator",
			Handler:    _BusinessManage_BusinessKnowledgeDataStatisticsBySceneAndCreator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "businessmanage/v1/business_manage.proto",
}
