server {
    listen 80;
    charset utf-8;
    client_max_body_size 10G;

    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index index.html index.htm;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        expires off;
    }

    location /assets/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=2592000, immutable";
        expires 30d;
    }

    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header Origin '';
        proxy_set_header Connection "";
        proxy_http_version 1.1;
        proxy_cache off;

        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Headers $http_access_control_request_headers;
        add_header Access-Control-Allow-Methods POST,GET,OPTIONS,DELETE,PUT,HEAD,PATCH;
        add_header Access-Control-Allow-Origin $http_origin;
        add_header Access-Control-Expose-Headers $http_access_control_request_headers;

        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://spring-server:8001;
    }

    location /data {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header Origin '';
        proxy_http_version 1.1;
        proxy_cache off;
        proxy_hide_header Cache-Control;
        proxy_hide_header Pragma;
        proxy_hide_header Expires;
        add_header Cache-Control "public, max-age=604800, immutable";
        expires 7d;

        proxy_pass http://spring-server:8001;
    }
}
