// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: rolemanage/v1/role.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RoleListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleListRequestMultiError, or nil if none found.
func (m *RoleListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPageSize() <= 0 {
		err := RoleListRequestValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageNumber() <= 0 {
		err := RoleListRequestValidationError{
			field:  "PageNumber",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSortBy() != "" {

		if _, ok := _RoleListRequest_SortBy_InLookup[m.GetSortBy()]; !ok {
			err := RoleListRequestValidationError{
				field:  "SortBy",
				reason: "value must be in list [id]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetOrder() != "" {

		if _, ok := _RoleListRequest_Order_InLookup[m.GetOrder()]; !ok {
			err := RoleListRequestValidationError{
				field:  "Order",
				reason: "value must be in list [asc desc]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for SearchRoleName

	// no validation rules for SearchRoleRemark

	if m.GetSearchRoleDisabled() != "" {

		if _, ok := _RoleListRequest_SearchRoleDisabled_InLookup[m.GetSearchRoleDisabled()]; !ok {
			err := RoleListRequestValidationError{
				field:  "SearchRoleDisabled",
				reason: "value must be in list [all disabled enabled]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return RoleListRequestMultiError(errors)
	}

	return nil
}

// RoleListRequestMultiError is an error wrapping multiple validation errors
// returned by RoleListRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleListRequestMultiError) AllErrors() []error { return m }

// RoleListRequestValidationError is the validation error returned by
// RoleListRequest.Validate if the designated constraints aren't met.
type RoleListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleListRequestValidationError) ErrorName() string { return "RoleListRequestValidationError" }

// Error satisfies the builtin error interface
func (e RoleListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleListRequestValidationError{}

var _RoleListRequest_SortBy_InLookup = map[string]struct{}{
	"id": {},
}

var _RoleListRequest_Order_InLookup = map[string]struct{}{
	"asc":  {},
	"desc": {},
}

var _RoleListRequest_SearchRoleDisabled_InLookup = map[string]struct{}{
	"all":      {},
	"disabled": {},
	"enabled":  {},
}

// Validate checks the field values on RoleListReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleListReplyMultiError, or
// nil if none found.
func (m *RoleListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetContent() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RoleListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RoleListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RoleListReplyValidationError{
					field:  fmt.Sprintf("Content[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalElements

	if len(errors) > 0 {
		return RoleListReplyMultiError(errors)
	}

	return nil
}

// RoleListReplyMultiError is an error wrapping multiple validation errors
// returned by RoleListReply.ValidateAll() if the designated constraints
// aren't met.
type RoleListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleListReplyMultiError) AllErrors() []error { return m }

// RoleListReplyValidationError is the validation error returned by
// RoleListReply.Validate if the designated constraints aren't met.
type RoleListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleListReplyValidationError) ErrorName() string { return "RoleListReplyValidationError" }

// Error satisfies the builtin error interface
func (e RoleListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleListReplyValidationError{}

// Validate checks the field values on RoleDetailRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleDetailRequestMultiError, or nil if none found.
func (m *RoleDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	if len(errors) > 0 {
		return RoleDetailRequestMultiError(errors)
	}

	return nil
}

// RoleDetailRequestMultiError is an error wrapping multiple validation errors
// returned by RoleDetailRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleDetailRequestMultiError) AllErrors() []error { return m }

// RoleDetailRequestValidationError is the validation error returned by
// RoleDetailRequest.Validate if the designated constraints aren't met.
type RoleDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleDetailRequestValidationError) ErrorName() string {
	return "RoleDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RoleDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleDetailRequestValidationError{}

// Validate checks the field values on RoleDetailReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleDetailReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleDetailReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleDetailReplyMultiError, or nil if none found.
func (m *RoleDetailReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleDetailReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRoleName()); l < 1 || l > 255 {
		err := RoleDetailReplyValidationError{
			field:  "RoleName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetRoleRemark()); l < 0 || l > 255 {
		err := RoleDetailReplyValidationError{
			field:  "RoleRemark",
			reason: "value length must be between 0 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsDisabled

	// no validation rules for IsUsed

	// no validation rules for IsBuiltin

	// no validation rules for UpdateTime

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return RoleDetailReplyMultiError(errors)
	}

	return nil
}

// RoleDetailReplyMultiError is an error wrapping multiple validation errors
// returned by RoleDetailReply.ValidateAll() if the designated constraints
// aren't met.
type RoleDetailReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleDetailReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleDetailReplyMultiError) AllErrors() []error { return m }

// RoleDetailReplyValidationError is the validation error returned by
// RoleDetailReply.Validate if the designated constraints aren't met.
type RoleDetailReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleDetailReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleDetailReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleDetailReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleDetailReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleDetailReplyValidationError) ErrorName() string { return "RoleDetailReplyValidationError" }

// Error satisfies the builtin error interface
func (e RoleDetailReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleDetailReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleDetailReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleDetailReplyValidationError{}

// Validate checks the field values on DeleteRoleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRoleRequestMultiError, or nil if none found.
func (m *DeleteRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	if len(errors) > 0 {
		return DeleteRoleRequestMultiError(errors)
	}

	return nil
}

// DeleteRoleRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteRoleRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRoleRequestMultiError) AllErrors() []error { return m }

// DeleteRoleRequestValidationError is the validation error returned by
// DeleteRoleRequest.Validate if the designated constraints aren't met.
type DeleteRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRoleRequestValidationError) ErrorName() string {
	return "DeleteRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRoleRequestValidationError{}

// Validate checks the field values on EditRoleDisabledRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EditRoleDisabledRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditRoleDisabledRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditRoleDisabledRequestMultiError, or nil if none found.
func (m *EditRoleDisabledRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditRoleDisabledRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	// no validation rules for IsDisabled

	if len(errors) > 0 {
		return EditRoleDisabledRequestMultiError(errors)
	}

	return nil
}

// EditRoleDisabledRequestMultiError is an error wrapping multiple validation
// errors returned by EditRoleDisabledRequest.ValidateAll() if the designated
// constraints aren't met.
type EditRoleDisabledRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditRoleDisabledRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditRoleDisabledRequestMultiError) AllErrors() []error { return m }

// EditRoleDisabledRequestValidationError is the validation error returned by
// EditRoleDisabledRequest.Validate if the designated constraints aren't met.
type EditRoleDisabledRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditRoleDisabledRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditRoleDisabledRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditRoleDisabledRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditRoleDisabledRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditRoleDisabledRequestValidationError) ErrorName() string {
	return "EditRoleDisabledRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EditRoleDisabledRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditRoleDisabledRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditRoleDisabledRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditRoleDisabledRequestValidationError{}

// Validate checks the field values on EditRoleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EditRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditRoleRequestMultiError, or nil if none found.
func (m *EditRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	if l := utf8.RuneCountInString(m.GetRoleName()); l < 1 || l > 255 {
		err := EditRoleRequestValidationError{
			field:  "RoleName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetRoleRemark()); l < 0 || l > 255 {
		err := EditRoleRequestValidationError{
			field:  "RoleRemark",
			reason: "value length must be between 0 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return EditRoleRequestMultiError(errors)
	}

	return nil
}

// EditRoleRequestMultiError is an error wrapping multiple validation errors
// returned by EditRoleRequest.ValidateAll() if the designated constraints
// aren't met.
type EditRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditRoleRequestMultiError) AllErrors() []error { return m }

// EditRoleRequestValidationError is the validation error returned by
// EditRoleRequest.Validate if the designated constraints aren't met.
type EditRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditRoleRequestValidationError) ErrorName() string { return "EditRoleRequestValidationError" }

// Error satisfies the builtin error interface
func (e EditRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditRoleRequestValidationError{}

// Validate checks the field values on AddRoleRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddRoleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddRoleRequestMultiError,
// or nil if none found.
func (m *AddRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRoleName()); l < 1 || l > 255 {
		err := AddRoleRequestValidationError{
			field:  "RoleName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetRoleRemark()); l < 0 || l > 255 {
		err := AddRoleRequestValidationError{
			field:  "RoleRemark",
			reason: "value length must be between 0 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddRoleRequestMultiError(errors)
	}

	return nil
}

// AddRoleRequestMultiError is an error wrapping multiple validation errors
// returned by AddRoleRequest.ValidateAll() if the designated constraints
// aren't met.
type AddRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddRoleRequestMultiError) AllErrors() []error { return m }

// AddRoleRequestValidationError is the validation error returned by
// AddRoleRequest.Validate if the designated constraints aren't met.
type AddRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddRoleRequestValidationError) ErrorName() string { return "AddRoleRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddRoleRequestValidationError{}

// Validate checks the field values on AddRoleReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddRoleReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddRoleReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddRoleReplyMultiError, or
// nil if none found.
func (m *AddRoleReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AddRoleReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	if len(errors) > 0 {
		return AddRoleReplyMultiError(errors)
	}

	return nil
}

// AddRoleReplyMultiError is an error wrapping multiple validation errors
// returned by AddRoleReply.ValidateAll() if the designated constraints aren't met.
type AddRoleReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddRoleReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddRoleReplyMultiError) AllErrors() []error { return m }

// AddRoleReplyValidationError is the validation error returned by
// AddRoleReply.Validate if the designated constraints aren't met.
type AddRoleReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddRoleReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddRoleReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddRoleReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddRoleReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddRoleReplyValidationError) ErrorName() string { return "AddRoleReplyValidationError" }

// Error satisfies the builtin error interface
func (e AddRoleReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddRoleReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddRoleReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddRoleReplyValidationError{}

// Validate checks the field values on RoleListReply_Role with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RoleListReply_Role) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleListReply_Role with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleListReply_RoleMultiError, or nil if none found.
func (m *RoleListReply_Role) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleListReply_Role) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleName

	// no validation rules for RoleRemark

	// no validation rules for IsUsed

	// no validation rules for IsBuiltin

	// no validation rules for IsDisabled

	// no validation rules for RoleId

	// no validation rules for UpdateTime

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return RoleListReply_RoleMultiError(errors)
	}

	return nil
}

// RoleListReply_RoleMultiError is an error wrapping multiple validation errors
// returned by RoleListReply_Role.ValidateAll() if the designated constraints
// aren't met.
type RoleListReply_RoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleListReply_RoleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleListReply_RoleMultiError) AllErrors() []error { return m }

// RoleListReply_RoleValidationError is the validation error returned by
// RoleListReply_Role.Validate if the designated constraints aren't met.
type RoleListReply_RoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleListReply_RoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleListReply_RoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleListReply_RoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleListReply_RoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleListReply_RoleValidationError) ErrorName() string {
	return "RoleListReply_RoleValidationError"
}

// Error satisfies the builtin error interface
func (e RoleListReply_RoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleListReply_Role.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleListReply_RoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleListReply_RoleValidationError{}
