// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: rolemanage/v1/role.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RoleManage_AddRole_FullMethodName          = "/api.rolemanage.v1.RoleManage/AddRole"
	RoleManage_EditRole_FullMethodName         = "/api.rolemanage.v1.RoleManage/EditRole"
	RoleManage_EditRoleDisabled_FullMethodName = "/api.rolemanage.v1.RoleManage/EditRoleDisabled"
	RoleManage_DeleteRole_FullMethodName       = "/api.rolemanage.v1.RoleManage/DeleteRole"
	RoleManage_RoleDetail_FullMethodName       = "/api.rolemanage.v1.RoleManage/RoleDetail"
	RoleManage_RoleList_FullMethodName         = "/api.rolemanage.v1.RoleManage/RoleList"
)

// RoleManageClient is the client API for RoleManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleManageClient interface {
	// 新增角色
	AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*AddRoleReply, error)
	// 编辑角色
	EditRole(ctx context.Context, in *EditRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 编辑角色状态
	EditRoleDisabled(ctx context.Context, in *EditRoleDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除角色
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 角色详情
	RoleDetail(ctx context.Context, in *RoleDetailRequest, opts ...grpc.CallOption) (*RoleDetailReply, error)
	// 角色列表
	RoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListReply, error)
}

type roleManageClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleManageClient(cc grpc.ClientConnInterface) RoleManageClient {
	return &roleManageClient{cc}
}

func (c *roleManageClient) AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*AddRoleReply, error) {
	out := new(AddRoleReply)
	err := c.cc.Invoke(ctx, RoleManage_AddRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManageClient) EditRole(ctx context.Context, in *EditRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoleManage_EditRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManageClient) EditRoleDisabled(ctx context.Context, in *EditRoleDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoleManage_EditRoleDisabled_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManageClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoleManage_DeleteRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManageClient) RoleDetail(ctx context.Context, in *RoleDetailRequest, opts ...grpc.CallOption) (*RoleDetailReply, error) {
	out := new(RoleDetailReply)
	err := c.cc.Invoke(ctx, RoleManage_RoleDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManageClient) RoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListReply, error) {
	out := new(RoleListReply)
	err := c.cc.Invoke(ctx, RoleManage_RoleList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleManageServer is the server API for RoleManage service.
// All implementations must embed UnimplementedRoleManageServer
// for forward compatibility
type RoleManageServer interface {
	// 新增角色
	AddRole(context.Context, *AddRoleRequest) (*AddRoleReply, error)
	// 编辑角色
	EditRole(context.Context, *EditRoleRequest) (*emptypb.Empty, error)
	// 编辑角色状态
	EditRoleDisabled(context.Context, *EditRoleDisabledRequest) (*emptypb.Empty, error)
	// 删除角色
	DeleteRole(context.Context, *DeleteRoleRequest) (*emptypb.Empty, error)
	// 角色详情
	RoleDetail(context.Context, *RoleDetailRequest) (*RoleDetailReply, error)
	// 角色列表
	RoleList(context.Context, *RoleListRequest) (*RoleListReply, error)
	mustEmbedUnimplementedRoleManageServer()
}

// UnimplementedRoleManageServer must be embedded to have forward compatible implementations.
type UnimplementedRoleManageServer struct {
}

func (UnimplementedRoleManageServer) AddRole(context.Context, *AddRoleRequest) (*AddRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRole not implemented")
}
func (UnimplementedRoleManageServer) EditRole(context.Context, *EditRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRole not implemented")
}
func (UnimplementedRoleManageServer) EditRoleDisabled(context.Context, *EditRoleDisabledRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRoleDisabled not implemented")
}
func (UnimplementedRoleManageServer) DeleteRole(context.Context, *DeleteRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedRoleManageServer) RoleDetail(context.Context, *RoleDetailRequest) (*RoleDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleDetail not implemented")
}
func (UnimplementedRoleManageServer) RoleList(context.Context, *RoleListRequest) (*RoleListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleList not implemented")
}
func (UnimplementedRoleManageServer) mustEmbedUnimplementedRoleManageServer() {}

// UnsafeRoleManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleManageServer will
// result in compilation errors.
type UnsafeRoleManageServer interface {
	mustEmbedUnimplementedRoleManageServer()
}

func RegisterRoleManageServer(s grpc.ServiceRegistrar, srv RoleManageServer) {
	s.RegisterService(&RoleManage_ServiceDesc, srv)
}

func _RoleManage_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManageServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManage_AddRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManageServer).AddRole(ctx, req.(*AddRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManage_EditRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManageServer).EditRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManage_EditRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManageServer).EditRole(ctx, req.(*EditRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManage_EditRoleDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRoleDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManageServer).EditRoleDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManage_EditRoleDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManageServer).EditRoleDisabled(ctx, req.(*EditRoleDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManage_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManageServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManage_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManageServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManage_RoleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManageServer).RoleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManage_RoleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManageServer).RoleDetail(ctx, req.(*RoleDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManage_RoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManageServer).RoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManage_RoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManageServer).RoleList(ctx, req.(*RoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleManage_ServiceDesc is the grpc.ServiceDesc for RoleManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rolemanage.v1.RoleManage",
	HandlerType: (*RoleManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRole",
			Handler:    _RoleManage_AddRole_Handler,
		},
		{
			MethodName: "EditRole",
			Handler:    _RoleManage_EditRole_Handler,
		},
		{
			MethodName: "EditRoleDisabled",
			Handler:    _RoleManage_EditRoleDisabled_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _RoleManage_DeleteRole_Handler,
		},
		{
			MethodName: "RoleDetail",
			Handler:    _RoleManage_RoleDetail_Handler,
		},
		{
			MethodName: "RoleList",
			Handler:    _RoleManage_RoleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rolemanage/v1/role.proto",
}
