// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: usermanage/v1/user.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginRequestMultiError, or
// nil if none found.
func (m *LoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserAccount

	// no validation rules for UserPassword

	if len(errors) > 0 {
		return LoginRequestMultiError(errors)
	}

	return nil
}

// LoginRequestMultiError is an error wrapping multiple validation errors
// returned by LoginRequest.ValidateAll() if the designated constraints aren't met.
type LoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginRequestMultiError) AllErrors() []error { return m }

// LoginRequestValidationError is the validation error returned by
// LoginRequest.Validate if the designated constraints aren't met.
type LoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestValidationError) ErrorName() string { return "LoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestValidationError{}

// Validate checks the field values on LoginReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginReplyMultiError, or
// nil if none found.
func (m *LoginReply) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return LoginReplyMultiError(errors)
	}

	return nil
}

// LoginReplyMultiError is an error wrapping multiple validation errors
// returned by LoginReply.ValidateAll() if the designated constraints aren't met.
type LoginReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginReplyMultiError) AllErrors() []error { return m }

// LoginReplyValidationError is the validation error returned by
// LoginReply.Validate if the designated constraints aren't met.
type LoginReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginReplyValidationError) ErrorName() string { return "LoginReplyValidationError" }

// Error satisfies the builtin error interface
func (e LoginReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginReplyValidationError{}

// Validate checks the field values on UserListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserListRequestMultiError, or nil if none found.
func (m *UserListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPageSize() <= 0 {
		err := UserListRequestValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageNumber() <= 0 {
		err := UserListRequestValidationError{
			field:  "PageNumber",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSortBy() != "" {

		if _, ok := _UserListRequest_SortBy_InLookup[m.GetSortBy()]; !ok {
			err := UserListRequestValidationError{
				field:  "SortBy",
				reason: "value must be in list [id]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetOrder() != "" {

		if _, ok := _UserListRequest_Order_InLookup[m.GetOrder()]; !ok {
			err := UserListRequestValidationError{
				field:  "Order",
				reason: "value must be in list [asc desc]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for SearchUserAccount

	// no validation rules for SearchUserNickname

	// no validation rules for SearchUserEmail

	// no validation rules for SearchUserPhoneNum

	// no validation rules for SearchUserSex

	if m.GetSearchUserDisabled() != "" {

		if _, ok := _UserListRequest_SearchUserDisabled_InLookup[m.GetSearchUserDisabled()]; !ok {
			err := UserListRequestValidationError{
				field:  "SearchUserDisabled",
				reason: "value must be in list [all disabled enabled]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return UserListRequestMultiError(errors)
	}

	return nil
}

// UserListRequestMultiError is an error wrapping multiple validation errors
// returned by UserListRequest.ValidateAll() if the designated constraints
// aren't met.
type UserListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserListRequestMultiError) AllErrors() []error { return m }

// UserListRequestValidationError is the validation error returned by
// UserListRequest.Validate if the designated constraints aren't met.
type UserListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserListRequestValidationError) ErrorName() string { return "UserListRequestValidationError" }

// Error satisfies the builtin error interface
func (e UserListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserListRequestValidationError{}

var _UserListRequest_SortBy_InLookup = map[string]struct{}{
	"id": {},
}

var _UserListRequest_Order_InLookup = map[string]struct{}{
	"asc":  {},
	"desc": {},
}

var _UserListRequest_SearchUserDisabled_InLookup = map[string]struct{}{
	"all":      {},
	"disabled": {},
	"enabled":  {},
}

// Validate checks the field values on UserListReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserListReplyMultiError, or
// nil if none found.
func (m *UserListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UserListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetContent() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserListReplyValidationError{
						field:  fmt.Sprintf("Content[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserListReplyValidationError{
					field:  fmt.Sprintf("Content[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalElements

	if len(errors) > 0 {
		return UserListReplyMultiError(errors)
	}

	return nil
}

// UserListReplyMultiError is an error wrapping multiple validation errors
// returned by UserListReply.ValidateAll() if the designated constraints
// aren't met.
type UserListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserListReplyMultiError) AllErrors() []error { return m }

// UserListReplyValidationError is the validation error returned by
// UserListReply.Validate if the designated constraints aren't met.
type UserListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserListReplyValidationError) ErrorName() string { return "UserListReplyValidationError" }

// Error satisfies the builtin error interface
func (e UserListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserListReplyValidationError{}

// Validate checks the field values on DeleteUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserRequestMultiError, or nil if none found.
func (m *DeleteUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return DeleteUserRequestMultiError(errors)
	}

	return nil
}

// DeleteUserRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteUserRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteUserRequestMultiError) AllErrors() []error { return m }

// DeleteUserRequestValidationError is the validation error returned by
// DeleteUserRequest.Validate if the designated constraints aren't met.
type DeleteUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteUserRequestValidationError) ErrorName() string {
	return "DeleteUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserRequestValidationError{}

// Validate checks the field values on ResetUserPasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetUserPasswordRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetUserPasswordRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetUserPasswordRequestMultiError, or nil if none found.
func (m *ResetUserPasswordRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetUserPasswordRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for UserPassword

	if len(errors) > 0 {
		return ResetUserPasswordRequestMultiError(errors)
	}

	return nil
}

// ResetUserPasswordRequestMultiError is an error wrapping multiple validation
// errors returned by ResetUserPasswordRequest.ValidateAll() if the designated
// constraints aren't met.
type ResetUserPasswordRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetUserPasswordRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetUserPasswordRequestMultiError) AllErrors() []error { return m }

// ResetUserPasswordRequestValidationError is the validation error returned by
// ResetUserPasswordRequest.Validate if the designated constraints aren't met.
type ResetUserPasswordRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetUserPasswordRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetUserPasswordRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetUserPasswordRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetUserPasswordRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetUserPasswordRequestValidationError) ErrorName() string {
	return "ResetUserPasswordRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResetUserPasswordRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetUserPasswordRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetUserPasswordRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetUserPasswordRequestValidationError{}

// Validate checks the field values on EditUserDisabledRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EditUserDisabledRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditUserDisabledRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditUserDisabledRequestMultiError, or nil if none found.
func (m *EditUserDisabledRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditUserDisabledRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for IsDisabled

	if len(errors) > 0 {
		return EditUserDisabledRequestMultiError(errors)
	}

	return nil
}

// EditUserDisabledRequestMultiError is an error wrapping multiple validation
// errors returned by EditUserDisabledRequest.ValidateAll() if the designated
// constraints aren't met.
type EditUserDisabledRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditUserDisabledRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditUserDisabledRequestMultiError) AllErrors() []error { return m }

// EditUserDisabledRequestValidationError is the validation error returned by
// EditUserDisabledRequest.Validate if the designated constraints aren't met.
type EditUserDisabledRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditUserDisabledRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditUserDisabledRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditUserDisabledRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditUserDisabledRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditUserDisabledRequestValidationError) ErrorName() string {
	return "EditUserDisabledRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EditUserDisabledRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditUserDisabledRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditUserDisabledRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditUserDisabledRequestValidationError{}

// Validate checks the field values on EditUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EditUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EditUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EditUserRequestMultiError, or nil if none found.
func (m *EditUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EditUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for UserNickname

	// no validation rules for UserEmail

	// no validation rules for UserPhoneNum

	// no validation rules for UserSex

	// no validation rules for UserPicture

	if len(errors) > 0 {
		return EditUserRequestMultiError(errors)
	}

	return nil
}

// EditUserRequestMultiError is an error wrapping multiple validation errors
// returned by EditUserRequest.ValidateAll() if the designated constraints
// aren't met.
type EditUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EditUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EditUserRequestMultiError) AllErrors() []error { return m }

// EditUserRequestValidationError is the validation error returned by
// EditUserRequest.Validate if the designated constraints aren't met.
type EditUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EditUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EditUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EditUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EditUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EditUserRequestValidationError) ErrorName() string { return "EditUserRequestValidationError" }

// Error satisfies the builtin error interface
func (e EditUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEditUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EditUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EditUserRequestValidationError{}

// Validate checks the field values on UserDetailRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserDetailRequestMultiError, or nil if none found.
func (m *UserDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return UserDetailRequestMultiError(errors)
	}

	return nil
}

// UserDetailRequestMultiError is an error wrapping multiple validation errors
// returned by UserDetailRequest.ValidateAll() if the designated constraints
// aren't met.
type UserDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDetailRequestMultiError) AllErrors() []error { return m }

// UserDetailRequestValidationError is the validation error returned by
// UserDetailRequest.Validate if the designated constraints aren't met.
type UserDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDetailRequestValidationError) ErrorName() string {
	return "UserDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDetailRequestValidationError{}

// Validate checks the field values on UserDetailReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserDetailReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserDetailReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserDetailReplyMultiError, or nil if none found.
func (m *UserDetailReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UserDetailReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserAccount

	// no validation rules for UserNickname

	// no validation rules for UserEmail

	// no validation rules for UserPhoneNum

	// no validation rules for UserSex

	// no validation rules for UserPicture

	// no validation rules for IsDisabled

	// no validation rules for IsBuiltin

	// no validation rules for UpdateTime

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return UserDetailReplyMultiError(errors)
	}

	return nil
}

// UserDetailReplyMultiError is an error wrapping multiple validation errors
// returned by UserDetailReply.ValidateAll() if the designated constraints
// aren't met.
type UserDetailReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDetailReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDetailReplyMultiError) AllErrors() []error { return m }

// UserDetailReplyValidationError is the validation error returned by
// UserDetailReply.Validate if the designated constraints aren't met.
type UserDetailReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDetailReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDetailReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDetailReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDetailReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDetailReplyValidationError) ErrorName() string { return "UserDetailReplyValidationError" }

// Error satisfies the builtin error interface
func (e UserDetailReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserDetailReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDetailReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDetailReplyValidationError{}

// Validate checks the field values on RandomPasswordReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RandomPasswordReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RandomPasswordReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RandomPasswordReplyMultiError, or nil if none found.
func (m *RandomPasswordReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RandomPasswordReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RandomPassword

	if len(errors) > 0 {
		return RandomPasswordReplyMultiError(errors)
	}

	return nil
}

// RandomPasswordReplyMultiError is an error wrapping multiple validation
// errors returned by RandomPasswordReply.ValidateAll() if the designated
// constraints aren't met.
type RandomPasswordReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RandomPasswordReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RandomPasswordReplyMultiError) AllErrors() []error { return m }

// RandomPasswordReplyValidationError is the validation error returned by
// RandomPasswordReply.Validate if the designated constraints aren't met.
type RandomPasswordReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RandomPasswordReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RandomPasswordReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RandomPasswordReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RandomPasswordReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RandomPasswordReplyValidationError) ErrorName() string {
	return "RandomPasswordReplyValidationError"
}

// Error satisfies the builtin error interface
func (e RandomPasswordReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRandomPasswordReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RandomPasswordReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RandomPasswordReplyValidationError{}

// Validate checks the field values on AddUserRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddUserRequestMultiError,
// or nil if none found.
func (m *AddUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUserAccount()); l < 1 || l > 50 {
		err := AddUserRequestValidationError{
			field:  "UserAccount",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserNickname()); l < 0 || l > 50 {
		err := AddUserRequestValidationError{
			field:  "UserNickname",
			reason: "value length must be between 0 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserEmail()); l < 0 || l > 255 {
		err := AddUserRequestValidationError{
			field:  "UserEmail",
			reason: "value length must be between 0 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserPhoneNum()); l < 0 || l > 11 {
		err := AddUserRequestValidationError{
			field:  "UserPhoneNum",
			reason: "value length must be between 0 and 11 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserSex() != "" {

		if _, ok := _AddUserRequest_UserSex_InLookup[m.GetUserSex()]; !ok {
			err := AddUserRequestValidationError{
				field:  "UserSex",
				reason: "value must be in list [男 女]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for UserPassword

	// no validation rules for UserPicture

	if len(errors) > 0 {
		return AddUserRequestMultiError(errors)
	}

	return nil
}

// AddUserRequestMultiError is an error wrapping multiple validation errors
// returned by AddUserRequest.ValidateAll() if the designated constraints
// aren't met.
type AddUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddUserRequestMultiError) AllErrors() []error { return m }

// AddUserRequestValidationError is the validation error returned by
// AddUserRequest.Validate if the designated constraints aren't met.
type AddUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddUserRequestValidationError) ErrorName() string { return "AddUserRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddUserRequestValidationError{}

var _AddUserRequest_UserSex_InLookup = map[string]struct{}{
	"男": {},
	"女": {},
}

// Validate checks the field values on AddUserReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddUserReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddUserReplyMultiError, or
// nil if none found.
func (m *AddUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AddUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return AddUserReplyMultiError(errors)
	}

	return nil
}

// AddUserReplyMultiError is an error wrapping multiple validation errors
// returned by AddUserReply.ValidateAll() if the designated constraints aren't met.
type AddUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddUserReplyMultiError) AllErrors() []error { return m }

// AddUserReplyValidationError is the validation error returned by
// AddUserReply.Validate if the designated constraints aren't met.
type AddUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddUserReplyValidationError) ErrorName() string { return "AddUserReplyValidationError" }

// Error satisfies the builtin error interface
func (e AddUserReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddUserReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddUserReplyValidationError{}

// Validate checks the field values on UserListReply_User with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserListReply_User) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserListReply_User with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserListReply_UserMultiError, or nil if none found.
func (m *UserListReply_User) ValidateAll() error {
	return m.validate(true)
}

func (m *UserListReply_User) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserAccount

	// no validation rules for UserNickname

	// no validation rules for UserEmail

	// no validation rules for UserPhoneNum

	// no validation rules for UserSex

	// no validation rules for UserPicture

	// no validation rules for IsDisabled

	// no validation rules for UserId

	// no validation rules for IsBuiltin

	// no validation rules for UpdateTime

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return UserListReply_UserMultiError(errors)
	}

	return nil
}

// UserListReply_UserMultiError is an error wrapping multiple validation errors
// returned by UserListReply_User.ValidateAll() if the designated constraints
// aren't met.
type UserListReply_UserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserListReply_UserMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserListReply_UserMultiError) AllErrors() []error { return m }

// UserListReply_UserValidationError is the validation error returned by
// UserListReply_User.Validate if the designated constraints aren't met.
type UserListReply_UserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserListReply_UserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserListReply_UserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserListReply_UserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserListReply_UserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserListReply_UserValidationError) ErrorName() string {
	return "UserListReply_UserValidationError"
}

// Error satisfies the builtin error interface
func (e UserListReply_UserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserListReply_User.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserListReply_UserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserListReply_UserValidationError{}
