version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
#      - /data/hci/frontend:/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /Users/kangdan/code/testdata:/data
      - ./log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime
#    depends_on:
#      - server
    networks:
      - knowledge-net
    ports:
      - "4444:81"
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    privileged: true
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./redis.conf:/usr/local/redis/conf/redis.conf
      - ./data/redis/db/:/data
    command: [ "redis-server", "/usr/local/redis/conf/redis.conf", "--appendonly", "yes" ]
    ports:
      - "16379:6379"
    networks:
      - knowledge-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./data/mysql/lib:/var/lib/mysql
      - ./mysql_shell:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "13306:3306"
    command: mysqld
    networks:
      - knowledge-net

#  server:
#    image: data-manage:v1.0
#    container_name: server
#    restart: always
#    privileged: true
#    volumes:
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime
#      - /Users/kangdan/code/gongye/data-mannagement/configs:/data/conf
#      - /Users/kangdan/code/gongye/data-mannagement/bin:/app
#    command: [ "./data-manage", "-conf", "/data/conf/config.yaml"]
#
#    ports:
##      - "8000:8000"
#      - "9000:9000"
#    depends_on:
#      - redis
#      - mysql
#    networks:
#      - knowledge-net

networks:
  knowledge-net: