module.exports = {
  content: [
    './src/pages/**/*.tsx',
    './src/components/**/*.tsx',
    './src/layouts/**/*.tsx',
  ],
  important: true,
  theme: {
    colors: {
      white: '#fff',
      primary: 'var(--primary)',
      primaryDeep: 'var(--primary-deep)',
      primaryLight1: 'var(--primary-light-1)',
      error: 'var(--error-color)',
      success: 'var(--green)',
      warning: 'var(--warning-color)',
      default: '#dfdfdf',
      bg: {
        pink: 'var(--pink)',
        pinkBg: 'var(--pink-bg)',
        green: 'var(--green)',
        greenBg: 'var(--green-bg)',
        blue: 'var(--blue)',
        blueBg: 'var(--blue-bg)',
        yellow: 'var(--yellow)',
        yellowBg: 'var(--yellow-bg)',
        cyan: 'var(--cyan)',
        cyanBg: 'var(--cyan-bg)',
        gray: 'var(--gray)',
        grayBg: 'var(--gray-bg)',
        1: 'var(--bg-1)',
        2: 'var(--bg-2)',
        3: 'var(--bg-3)',
        4: 'var(--bg-4)',
      },
      qaGray: {
        100: 'var(--gray-100)',
        200: 'var(--gray-200)',
        500: 'var(--gray)',
      },
      text: {
        1: 'var(--text-1)',
        1.1: 'var(--text-1-1)',
        2: 'var(--text-2)',
        3: 'var(--text-3)',
        4: 'var(--text-4)',
      },
      link: 'var(--link)',
    },
    spacing: {
      4: '4px',
      8: '8px',
      10: '10px',
      12: '12px',
      16: '16px',
      24: '24px',
      32: '32px',
      48: '48px',
    },
    extend: {},
  },
  plugins: [],
};
