// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/kangdan0404/backend-of-knowledge-base/internal/biz"
	"gitee.com/kangdan0404/backend-of-knowledge-base/internal/conf"
	"gitee.com/kangdan0404/backend-of-knowledge-base/internal/data"
	"gitee.com/kangdan0404/backend-of-knowledge-base/internal/server"
	"gitee.com/kangdan0404/backend-of-knowledge-base/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewRds(confData)
	engine := data.NewDB(confData, client)
	dataData, cleanup, err := data.NewData(engine, client)
	if err != nil {
		return nil, nil, err
	}
	roleMangeRepo := data.NewRoleMangeRepo(dataData, logger)
	roleManageUC := biz.NewRoleManageUC(roleMangeRepo, logger, confData)
	roleManageService := service.NewRoleManageService(roleManageUC)
	userMangeRepo := data.NewUserMangeRepo(dataData, logger)
	userManageUC := biz.NewUserManageUC(userMangeRepo, logger, confData)
	userManageService := service.NewUserManageService(userManageUC)
	dataMangeRepo := data.NewDataMangeRepo(dataData, logger)
	dataManageUC := biz.NewDataManageUC(dataMangeRepo, logger)
	dataManageService := service.NewDataManageService(dataManageUC)
	dictMangeRepo := data.NewDictMangeRepo(dataData, logger)
	dictManageUC := biz.NewDictManageUC(dictMangeRepo, logger)
	dictManageService := service.NewDictManageService(dictManageUC)
	sceneMangeRepo := data.NewSceneMangeRepo(dataData, logger)
	sceneManageUC := biz.NewSceneManageUC(sceneMangeRepo, logger)
	sceneManageService := service.NewSceneManageService(sceneManageUC)
	businessMangeRepo := data.NewBusinessMangeRepo(dataData, logger)
	businessManageUC := biz.NewBusinessManageUC(businessMangeRepo, logger, confData)
	businessManageService := service.NewBusinessManageService(businessManageUC, confData)
	grpcServer := server.NewGRPCServer(confServer, roleManageService, userManageService, dataManageService, dictManageService, sceneManageService, businessManageService, logger)
	httpServer := server.NewHTTPServer(confServer, roleManageService, dataManageService, dictManageService, sceneManageService, businessManageService, userManageService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
