// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.2
// - protoc             v5.29.3
// source: usermanage/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserManageAddUser = "/api.usermanage.v1.UserManage/AddUser"
const OperationUserManageCurrentUserDetail = "/api.usermanage.v1.UserManage/CurrentUserDetail"
const OperationUserManageDeleteUser = "/api.usermanage.v1.UserManage/DeleteUser"
const OperationUserManageEditUser = "/api.usermanage.v1.UserManage/EditUser"
const OperationUserManageEditUserDisabled = "/api.usermanage.v1.UserManage/EditUserDisabled"
const OperationUserManageLogin = "/api.usermanage.v1.UserManage/Login"
const OperationUserManageRandomPassword = "/api.usermanage.v1.UserManage/RandomPassword"
const OperationUserManageResetUserPassword = "/api.usermanage.v1.UserManage/ResetUserPassword"
const OperationUserManageUserDetail = "/api.usermanage.v1.UserManage/UserDetail"
const OperationUserManageUserList = "/api.usermanage.v1.UserManage/UserList"

type UserManageHTTPServer interface {
	// AddUser新增用户
	AddUser(context.Context, *AddUserRequest) (*AddUserReply, error)
	// CurrentUserDetail 当前登陆用户详情
	CurrentUserDetail(context.Context, *emptypb.Empty) (*UserDetailReply, error)
	// DeleteUser 删除用户
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	// EditUser 编辑用户
	EditUser(context.Context, *EditUserRequest) (*emptypb.Empty, error)
	// EditUserDisabled 编辑用户状态
	EditUserDisabled(context.Context, *EditUserDisabledRequest) (*emptypb.Empty, error)
	// Login 登陆
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// RandomPassword 生成随机密码
	RandomPassword(context.Context, *emptypb.Empty) (*RandomPasswordReply, error)
	// ResetUserPassword 重置用户密码
	ResetUserPassword(context.Context, *ResetUserPasswordRequest) (*emptypb.Empty, error)
	// UserDetail 用户详情
	UserDetail(context.Context, *UserDetailRequest) (*UserDetailReply, error)
	// UserList 用户列表
	UserList(context.Context, *UserListRequest) (*UserListReply, error)
}

func RegisterUserManageHTTPServer(s *http.Server, srv UserManageHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/data/user/add", _UserManage_AddUser0_HTTP_Handler(srv))
	r.GET("/v1/data/user/password/random", _UserManage_RandomPassword0_HTTP_Handler(srv))
	r.GET("/v1/data/user/detail", _UserManage_UserDetail0_HTTP_Handler(srv))
	r.GET("/v1/data/user/current/detail", _UserManage_CurrentUserDetail0_HTTP_Handler(srv))
	r.POST("/v1/data/user/edit", _UserManage_EditUser0_HTTP_Handler(srv))
	r.POST("/v1/data/user/edit/status", _UserManage_EditUserDisabled0_HTTP_Handler(srv))
	r.POST("/v1/data/user/password/reset", _UserManage_ResetUserPassword0_HTTP_Handler(srv))
	r.POST("/v1/data/user/delete", _UserManage_DeleteUser0_HTTP_Handler(srv))
	r.GET("/v1/data/user/list", _UserManage_UserList0_HTTP_Handler(srv))
	r.GET("/v1/data/user/login", _UserManage_Login0_HTTP_Handler(srv))
}

func _UserManage_AddUser0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageAddUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddUser(ctx, req.(*AddUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddUserReply)
		return ctx.Result(200, reply)
	}
}

func _UserManage_RandomPassword0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageRandomPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RandomPassword(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RandomPasswordReply)
		return ctx.Result(200, reply)
	}
}

func _UserManage_UserDetail0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageUserDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserDetail(ctx, req.(*UserDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserDetailReply)
		return ctx.Result(200, reply)
	}
}

func _UserManage_CurrentUserDetail0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageCurrentUserDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CurrentUserDetail(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserDetailReply)
		return ctx.Result(200, reply)
	}
}

func _UserManage_EditUser0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EditUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageEditUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EditUser(ctx, req.(*EditUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserManage_EditUserDisabled0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EditUserDisabledRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageEditUserDisabled)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EditUserDisabled(ctx, req.(*EditUserDisabledRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserManage_ResetUserPassword0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResetUserPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageResetUserPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResetUserPassword(ctx, req.(*ResetUserPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserManage_DeleteUser0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageDeleteUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteUser(ctx, req.(*DeleteUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserManage_UserList0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageUserList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserList(ctx, req.(*UserListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserListReply)
		return ctx.Result(200, reply)
	}
}

func _UserManage_Login0_HTTP_Handler(srv UserManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManageLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

type UserManageHTTPClient interface {
	AddUser(ctx context.Context, req *AddUserRequest, opts ...http.CallOption) (rsp *AddUserReply, err error)
	CurrentUserDetail(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *UserDetailReply, err error)
	DeleteUser(ctx context.Context, req *DeleteUserRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	EditUser(ctx context.Context, req *EditUserRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	EditUserDisabled(ctx context.Context, req *EditUserDisabledRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	RandomPassword(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *RandomPasswordReply, err error)
	ResetUserPassword(ctx context.Context, req *ResetUserPasswordRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UserDetail(ctx context.Context, req *UserDetailRequest, opts ...http.CallOption) (rsp *UserDetailReply, err error)
	UserList(ctx context.Context, req *UserListRequest, opts ...http.CallOption) (rsp *UserListReply, err error)
}

type UserManageHTTPClientImpl struct {
	cc *http.Client
}

func NewUserManageHTTPClient(client *http.Client) UserManageHTTPClient {
	return &UserManageHTTPClientImpl{client}
}

func (c *UserManageHTTPClientImpl) AddUser(ctx context.Context, in *AddUserRequest, opts ...http.CallOption) (*AddUserReply, error) {
	var out AddUserReply
	pattern := "/v1/data/user/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserManageAddUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) CurrentUserDetail(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*UserDetailReply, error) {
	var out UserDetailReply
	pattern := "/v1/data/user/current/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManageCurrentUserDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/user/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserManageDeleteUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) EditUser(ctx context.Context, in *EditUserRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/user/edit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserManageEditUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) EditUserDisabled(ctx context.Context, in *EditUserDisabledRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/user/edit/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserManageEditUserDisabled))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/data/user/login"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManageLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) RandomPassword(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*RandomPasswordReply, error) {
	var out RandomPasswordReply
	pattern := "/v1/data/user/password/random"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManageRandomPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) ResetUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/data/user/password/reset"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserManageResetUserPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) UserDetail(ctx context.Context, in *UserDetailRequest, opts ...http.CallOption) (*UserDetailReply, error) {
	var out UserDetailReply
	pattern := "/v1/data/user/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManageUserDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserManageHTTPClientImpl) UserList(ctx context.Context, in *UserListRequest, opts ...http.CallOption) (*UserListReply, error) {
	var out UserListReply
	pattern := "/v1/data/user/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManageUserList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
